modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "xerca"
logoFile = "assets/xercatools/textures/icon.png"
description = '''
Useful tools and fun weapons
'''

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
