package xerca.xercafood.common.item;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.item.crafting.SimpleCraftingRecipeSerializer;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.ComposterBlock;
import xerca.xercafood.common.XercaFood;
import xerca.xercafood.common.block.BlockPizza;
import xerca.xercafood.common.block.Blocks;
import xerca.xercafood.common.crafting.RecipeTeaFilling;
import xerca.xercafood.common.crafting.RecipeTeaPouring;
import xerca.xercafood.common.crafting.RecipeTeaRefilling;
import xerca.xercafood.common.crafting.RecipeTeaSugaring;

public final class Items {
    public static final Item ITEM_KNIFE = new ItemKnife();
    public static final Item ITEM_GLASS = new ItemGlass();
    public static final Item ENDER_CUPCAKE = new ItemEnderCupcake();
    public static final Item COLA_EXTRACT = new Item(new Item.Properties().craftRemainder(net.minecraft.world.item.Items.GLASS_BOTTLE));
    public static final Item COLA_POWDER = new Item(new Item.Properties());
    public static final Item ITEM_ULTIMATE_BURGER = new ItemUltimateBurger();
    public static final Item ITEM_GLASS_OF_WATER = new ItemGlassOfWater(new Item.Properties().food(Foods.GLASS_OF_WATER), ITEM_GLASS);
    public static final Item ITEM_APPLE_PIE = new BlockItem(Blocks.BLOCK_APPLE_PIE, new Item.Properties());
    public static final Item SWEET_BERRY_PIE = new BlockItem(Blocks.BLOCK_SWEET_BERRY_PIE, new Item.Properties());
    public static final Item ITEM_TEACUP = new ItemTea(new Item.Properties());
    public static final ItemTeacup ITEM_FULL_TEACUP_0 = new ItemTeacup(0, ITEM_TEACUP);
    public static final ItemTeacup ITEM_FULL_TEACUP_1 = new ItemTeacup(1, ITEM_TEACUP);
    public static final ItemTeacup ITEM_FULL_TEACUP_2 = new ItemTeacup(2, ITEM_TEACUP);
    public static final ItemTeacup ITEM_FULL_TEACUP_3 = new ItemTeacup(3, ITEM_TEACUP);
    public static final ItemTeacup ITEM_FULL_TEACUP_4 = new ItemTeacup(4, ITEM_TEACUP);
    public static final ItemTeacup ITEM_FULL_TEACUP_5 = new ItemTeacup(5, ITEM_TEACUP);
    public static final ItemTeacup ITEM_FULL_TEACUP_6 = new ItemTeacup(6, ITEM_TEACUP);
    public static final ItemTeapot ITEM_FULL_TEAPOT_0 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 0, false);
    public static final ItemTeapot ITEM_FULL_TEAPOT_1 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 1, false);
    public static final ItemTeapot ITEM_FULL_TEAPOT_2 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 2, false);
    public static final ItemTeapot ITEM_FULL_TEAPOT_3 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 3, false);
    public static final ItemTeapot ITEM_FULL_TEAPOT_4 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 4, false);
    public static final ItemTeapot ITEM_FULL_TEAPOT_5 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 5, false);
    public static final ItemTeapot ITEM_FULL_TEAPOT_6 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 6, false);
    public static final ItemTeapot ITEM_FULL_TEAPOT_7 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 7, false);
    public static final ItemTeapot ITEM_HOT_TEAPOT_0 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 0, true);
    public static final ItemTeapot ITEM_HOT_TEAPOT_1 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 1, true);
    public static final ItemTeapot ITEM_HOT_TEAPOT_2 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 2, true);
    public static final ItemTeapot ITEM_HOT_TEAPOT_3 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 3, true);
    public static final ItemTeapot ITEM_HOT_TEAPOT_4 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 4, true);
    public static final ItemTeapot ITEM_HOT_TEAPOT_5 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 5, true);
    public static final ItemTeapot ITEM_HOT_TEAPOT_6 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 6, true);
    public static final ItemTeapot ITEM_HOT_TEAPOT_7 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 7, true);
    public static final ItemEmptyTeapot ITEM_TEAPOT = new ItemEmptyTeapot(new Item.Properties());
    public static final Item ITEM_TEA_SEEDS = new BlockItem(Blocks.BLOCK_TEA_PLANT, new Item.Properties());
    public static final Item ITEM_TEA_DRIED = new ItemTea(new Item.Properties());
    public static final Item ITEM_TEA_LEAF = new ItemTea(new Item.Properties());
    public static final ItemGoldenCupcake ITEM_GOLDEN_CUPCAKE = new ItemGoldenCupcake();
    public static final ItemTomato ITEM_TOMATO = new ItemTomato();
    public static final Item ITEM_TOMATO_SEEDS = new BlockItem(Blocks.BLOCK_TOMATO_PLANT, new Item.Properties());
    public static final Item ITEM_RICE_SEEDS = new BlockItem(Blocks.BLOCK_RICE_PLANT, new Item.Properties());
    public static final Item VAT = new BlockItem(Blocks.VAT, new Item.Properties());
    public static final Item CHEESE_WHEEL = new BlockItem(Blocks.CHEESE_WHEEL, new Item.Properties());
    public static final Item ITEM_APPLE_CUPCAKE = makeFoodItem(Foods.APPLE_CUPCAKE);
    public static final Item ITEM_PUMPKIN_CUPCAKE = makeFoodItem(Foods.PUMPKIN_CUPCAKE);
    public static final Item ITEM_COCOA_CUPCAKE = makeFoodItem(Foods.COCOA_CUPCAKE);
    public static final Item ITEM_MELON_CUPCAKE = makeFoodItem(Foods.MELON_CUPCAKE);
    public static final Item ITEM_CARROT_CUPCAKE = makeFoodItem(Foods.CARROT_CUPCAKE);
    public static final Item ITEM_FANCY_APPLE_CUPCAKE = makeFoodItem(Foods.FANCY_APPLE_CUPCAKE);
    public static final Item ITEM_FANCY_PUMPKIN_CUPCAKE = makeFoodItem(Foods.FANCY_PUMPKIN_CUPCAKE);
    public static final Item GLOWBERRY_CUPCAKE = makeFoodItem(Foods.GLOWBERRY_CUPCAKE);
    public static final Item ITEM_DONUT = makeFoodItem(Foods.DONUT);
    public static final Item ITEM_FANCY_DONUT = makeFoodItem(Foods.FANCY_DONUT);
    public static final Item ITEM_SPRINKLES = makeFoodItem(Foods.SPRINKLES);
    public static final Item ITEM_CHOCOLATE = makeFoodItem(Foods.CHOCOLATE);
    public static final Item ITEM_BUN = makeFoodItem(Foods.BUN);
    public static final Item ITEM_RAW_PATTY = makeFoodItem(Foods.RAW_PATTY);
    public static final Item ITEM_COOKED_PATTY = makeFoodItem(Foods.COOKED_PATTY);
    public static final Item ITEM_RAW_CHICKEN_PATTY = makeFoodItem(Foods.RAW_CHICKEN_PATTY);
    public static final Item ITEM_COOKED_CHICKEN_PATTY = makeFoodItem(Foods.COOKED_CHICKEN_PATTY);
    public static final Item ITEM_HAMBURGER = makeFoodItem(Foods.HAMBURGER);
    public static final Item ITEM_CHICKEN_BURGER = makeFoodItem(Foods.CHICKEN_BURGER);
    public static final Item ITEM_MUSHROOM_BURGER = makeFoodItem(Foods.MUSHROOM_BURGER);
    public static final Item ITEM_ULTIMATE_BOTTOM = makeFoodItem(Foods.ULTIMATE_BOTTOM);
    public static final Item ITEM_ULTIMATE_TOP = makeFoodItem(Foods.ULTIMATE_TOP);
    public static final Item CHEESEBURGER = makeFoodItem(Foods.CHEESEBURGER);
    public static final Item ITEM_ROTTEN_BURGER = makeFoodItem( Foods.ROTTEN_BURGER);
    public static final Item ITEM_RAW_SAUSAGE = makeFoodItem(Foods.RAW_SAUSAGE);
    public static final Item ITEM_COOKED_SAUSAGE = makeFoodItem(Foods.COOKED_SAUSAGE);
    public static final Item ITEM_HOTDOG = makeFoodItem(Foods.HOTDOG);
    public static final Item ITEM_FISH_BREAD = makeFoodItem(Foods.FISH_BREAD);
    public static final Item ITEM_DAISY_SANDWICH = makeFoodItem( Foods.DAISY_SANDWICH);
    public static final Item ITEM_CHICKEN_WRAP = makeFoodItem(Foods.CHICKEN_WRAP);
    public static final Item ITEM_RAW_SCHNITZEL = makeFoodItem(Foods.RAW_SCHNITZEL);
    public static final Item ITEM_COOKED_SCHNITZEL = makeFoodItem(Foods.COOKED_SCHNITZEL);
    public static final Item ITEM_FRIED_EGG = makeFoodItem(Foods.FRIED_EGG);
    public static final Item ITEM_CROISSANT = makeFoodItem( Foods.CROISSANT);
    public static final Item ITEM_POTATO_SLICES = makeFoodItem( Foods.POTATO_SLICES);
    public static final Item ITEM_POTATO_FRIES = makeFoodItem( Foods.POTATO_FRIES);
    public static final Item ITEM_SHISH_KEBAB = makeFoodItem( Foods.SHISH_KEBAB);
    public static final Item ITEM_TOMATO_SLICES = makeFoodItem(Foods.TOMATO_SLICES);
    public static final Item ITEM_ICE_TEA = makeDrinkItem(Foods.ICE_TEA, ITEM_GLASS);
    public static final Item ITEM_APPLE_JUICE = makeDrinkItem(Foods.APPLE_JUICE, ITEM_GLASS);
    public static final Item ITEM_CARROT_JUICE = makeDrinkItem(Foods.CARROT_JUICE, ITEM_GLASS);
    public static final Item ITEM_MELON_JUICE = makeDrinkItem(Foods.MELON_JUICE, ITEM_GLASS);
    public static final Item ITEM_PUMPKIN_JUICE = makeDrinkItem(Foods.PUMPKIN_JUICE, ITEM_GLASS);
    public static final Item ITEM_TOMATO_JUICE = makeDrinkItem(Foods.TOMATO_JUICE, ITEM_GLASS);
    public static final Item ITEM_WHEAT_JUICE = makeDrinkItem(Foods.WHEAT_JUICE, ITEM_GLASS);
    public static final Item ITEM_GLASS_OF_MILK = makeDrinkItem(Foods.GLASS_OF_MILK, ITEM_GLASS);
    public static final Item SWEET_BERRY_JUICE = makeDrinkItem(Foods.SWEET_BERRY_JUICE, ITEM_GLASS);
    public static final Item ITEM_AYRAN = makeDrinkItem(Foods.AYRAN, ITEM_GLASS);
    public static final Item SAKE = makeDrinkItem(Foods.SAKE, ITEM_GLASS);
    public static final Item CARBONATED_WATER = makeDrinkItem(Foods.CARBONATED_WATER, ITEM_GLASS);
    public static final Item SODA = makeDrinkItem(Foods.SODA, ITEM_GLASS);
    public static final Item COLA = makeDrinkItem(Foods.COLA, ITEM_GLASS);
    public static final Item OYAKODON = makeContainedFoodItem(Foods.OYAKODON, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item BEEF_DONBURI = makeContainedFoodItem(Foods.BEEF_DONBURI, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item EGG_SUSHI = makeFoodItem(Foods.EGG_SUSHI);
    public static final Item NIGIRI_SUSHI = makeFoodItem(Foods.NIGIRI_SUSHI);
    public static final Item OMURICE = makeFoodItem(Foods.OMURICE);
    public static final Item RICEBALL = makeFoodItem(Foods.RICEBALL);
    public static final Item SUSHI = makeFoodItem(Foods.SUSHI);
    public static final Item COOKED_RICE = makeFoodItem(Foods.COOKED_RICE);
    public static final Item SASHIMI = makeFoodItem(Foods.SASHIMI);
    public static final Item RICE_PUDDING = makeContainedFoodItem(Foods.RICE_PUDDING, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item BAKED_RICE_PUDDING = makeContainedFoodItem(Foods.BAKED_RICE_PUDDING, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item SWEET_BERRY_CUPCAKE_FANCY = makeFoodItem(Foods.SWEET_BERRY_CUPCAKE_FANCY);
    public static final Item SWEET_BERRY_CUPCAKE = makeFoodItem(Foods.SWEET_BERRY_CUPCAKE);
    public static final Item DONER_SLICE = makeFoodItem(Foods.DONER_SLICE);
    public static final Item ITEM_YOGHURT = makeContainedFoodItem(Foods.YOGHURT, net.minecraft.world.item.Items.BUCKET, 16);
    public static final Item ITEM_HONEYBERRY_YOGHURT = makeContainedFoodItem(Foods.HONEYBERRY_YOGHURT, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item ITEM_HONEY_CUPCAKE = makeFoodItem(Foods.HONEY_CUPCAKE);
    public static final Item ITEM_DONER_WRAP = makeFoodItem(Foods.DONER_WRAP);
    public static final Item ITEM_CHUBBY_DONER = makeFoodItem(Foods.CHUBBY_DONER);
    public static final Item ITEM_ALEXANDER = makeContainedFoodItem(Foods.ALEXANDER, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item RAW_SHISH_KEBAB = makeFoodItem(Foods.RAW_SHISH_KEBAB);
    public static final Item CHEESE_SLICE = makeFoodItem(Foods.CHEESE_SLICE);
    public static final Item CHEESE_TOAST = makeFoodItem(Foods.CHEESE_TOAST);
    public static final Item SQUID_INK_PAELLA = makeContainedFoodItem(Foods.SQUID_INK_PAELLA, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item GLOW_SQUID_INK_PAELLA = makeContainedFoodItem(Foods.GLOW_SQUID_INK_PAELLA, net.minecraft.world.item.Items.BOWL, 16);

    public static final Item RAW_PIZZA_PEPPERONI_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MUSHROOM_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MUSHROOM_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MUSHROOM_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MEAT_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MEAT_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MEAT_MEAT = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MEAT_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MEAT_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MEAT_MEAT = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_FISH_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_FISH_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_FISH_MEAT = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_FISH_FISH = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MEAT_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MEAT_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MEAT_MEAT = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_FISH_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_FISH_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_FISH_MEAT = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_FISH_FISH = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_MEAT = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_FISH = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_CHICKEN = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MEAT_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MEAT_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MEAT_MEAT = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_FISH_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_FISH_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_FISH_MEAT = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_FISH_FISH = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_MEAT = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_FISH = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA_MEAT = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA_FISH = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA_CHICKEN = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA = new ItemRawPizza(BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_0);
    public static final Item PIZZA_PEPPERONI_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_PEPPERONI_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MUSHROOM_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_MUSHROOM_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MUSHROOM_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_MUSHROOM_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MUSHROOM_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_MUSHROOM_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_MEAT_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_MEAT_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MEAT_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_MEAT_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MEAT_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_MEAT_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_MEAT_MEAT_PEPPERONI = new ItemPizza(Blocks.PIZZA_MEAT_MEAT_PEPPERONI, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MEAT_MEAT_MUSHROOM = new ItemPizza(Blocks.PIZZA_MEAT_MEAT_MUSHROOM, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_MEAT_MEAT_MEAT = new ItemPizza(Blocks.PIZZA_MEAT_MEAT_MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_FISH_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_FISH_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_FISH_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_FISH_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_FISH_MEAT_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_MEAT_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_FISH_MEAT_MUSHROOM = new ItemPizza(Blocks.PIZZA_FISH_MEAT_MUSHROOM, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_FISH_MEAT_MEAT = new ItemPizza(Blocks.PIZZA_FISH_MEAT_MEAT, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_FISH_FISH_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_FISH_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_FISH_FISH_MUSHROOM = new ItemPizza(Blocks.PIZZA_FISH_FISH_MUSHROOM, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_FISH_FISH_MEAT = new ItemPizza(Blocks.PIZZA_FISH_FISH_MEAT, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_FISH_FISH_FISH = new ItemPizza(Blocks.PIZZA_FISH_FISH_FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH);
    public static final Item PIZZA_CHICKEN_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_CHICKEN_MEAT_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_MEAT_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_MEAT_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_MEAT_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_CHICKEN_MEAT_MEAT = new ItemPizza(Blocks.PIZZA_CHICKEN_MEAT_MEAT, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_CHICKEN_FISH_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_FISH_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_CHICKEN_FISH_MEAT = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH_MEAT, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_CHICKEN_FISH_FISH = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH_FISH, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH);
    public static final Item PIZZA_CHICKEN_CHICKEN_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_CHICKEN_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_CHICKEN_CHICKEN_MEAT = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_MEAT, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_CHICKEN_CHICKEN_FISH = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_FISH, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH);
    public static final Item PIZZA_CHICKEN_CHICKEN_CHICKEN = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN);
    public static final Item PIZZA_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MEAT_PEPPERONI = new ItemPizza(Blocks.PIZZA_MEAT_PEPPERONI, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MEAT_MUSHROOM = new ItemPizza(Blocks.PIZZA_MEAT_MUSHROOM, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MEAT_MEAT = new ItemPizza(Blocks.PIZZA_MEAT_MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH_MUSHROOM = new ItemPizza(Blocks.PIZZA_FISH_MUSHROOM, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH_MEAT = new ItemPizza(Blocks.PIZZA_FISH_MEAT, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH_FISH = new ItemPizza(Blocks.PIZZA_FISH_FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_MEAT = new ItemPizza(Blocks.PIZZA_CHICKEN_MEAT, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_FISH = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_CHICKEN = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_PEPPERONI = new ItemPizza(Blocks.PIZZA_PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MUSHROOM = new ItemPizza(Blocks.PIZZA_MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MEAT = new ItemPizza(Blocks.PIZZA_MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH = new ItemPizza(Blocks.PIZZA_FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN = new ItemPizza(Blocks.PIZZA_CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA = new ItemPizza(Blocks.PIZZA, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);

//    public static final CreativeModeTab teaTab = FabricItemGroup.builder(new ResourceLocation(XercaFood.MODID, "tea_tab"))
//            .icon(() -> new ItemStack(Items.ITEM_FULL_TEAPOT_1))
//            .displayItems((enabledFeatures, entries, operatorEnabled) -> {
//                entries.accept(ITEM_TEACUP);
//                entries.accept(ITEM_TEA_LEAF);
//                entries.accept(ITEM_TEA_DRIED);
//                entries.accept(ITEM_TEAPOT);
//                entries.accept(ITEM_FULL_TEACUP_0);
//                entries.accept(ITEM_HOT_TEAPOT_7);
//            })
//            .build();

    public static final RecipeSerializer<RecipeTeaSugaring> CRAFTING_SPECIAL_TEA_SUGARING = new SimpleCraftingRecipeSerializer<>(RecipeTeaSugaring::new);
    public static final RecipeSerializer<RecipeTeaPouring> CRAFTING_SPECIAL_TEA_POURING = new SimpleCraftingRecipeSerializer<>(RecipeTeaPouring::new);
    public static final RecipeSerializer<RecipeTeaFilling> CRAFTING_SPECIAL_TEA_FILLING = new SimpleCraftingRecipeSerializer<>(RecipeTeaFilling::new);
    public static final RecipeSerializer<RecipeTeaRefilling> CRAFTING_SPECIAL_TEA_REFILLING = new SimpleCraftingRecipeSerializer<>(RecipeTeaRefilling::new);

    static Item makeFoodItem(FoodProperties food){
        return new Item(new Item.Properties().food(food));
    }

    static Item makeContainedFoodItem(FoodProperties food, Item container, int stackSize){
        return new ItemStackableContainedFood(new Item.Properties().food(food).
                craftRemainder(container), container, stackSize);
    }

    static Item makeDrinkItem(FoodProperties food, Item container){
        return new ItemDrink(new Item.Properties().food(food), container);
    }

    private static void registerItem(String name, Item item) {
        Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(XercaFood.MODID, name), item);
    }

    static void registerCompostable(float chance, ItemLike itemIn) {
        ComposterBlock.COMPOSTABLES.put(itemIn.asItem(), chance);
    }

    public static void registerCompostables() {
        registerCompostable(0.3f, ITEM_TEA_SEEDS);
        registerCompostable(0.3f, ITEM_TOMATO_SEEDS);
        registerCompostable(0.3f, ITEM_RICE_SEEDS);
        registerCompostable(0.65f, ITEM_TOMATO);
        registerCompostable(0.65f, ITEM_TEA_DRIED);
        registerCompostable(0.65f, ITEM_TEA_LEAF);
    }

    public static void registerRecipes() {
        Registry.register(BuiltInRegistries.RECIPE_SERIALIZER, new ResourceLocation(XercaFood.MODID, "crafting_special_tea_sugaring"), CRAFTING_SPECIAL_TEA_SUGARING);
        Registry.register(BuiltInRegistries.RECIPE_SERIALIZER, new ResourceLocation(XercaFood.MODID, "crafting_special_tea_pouring"), CRAFTING_SPECIAL_TEA_POURING);
        Registry.register(BuiltInRegistries.RECIPE_SERIALIZER, new ResourceLocation(XercaFood.MODID, "crafting_special_tea_filling"), CRAFTING_SPECIAL_TEA_FILLING);
        Registry.register(BuiltInRegistries.RECIPE_SERIALIZER, new ResourceLocation(XercaFood.MODID, "crafting_special_tea_refilling"), CRAFTING_SPECIAL_TEA_REFILLING);
    }

    public static void registerItems() {
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.FOOD_AND_DRINKS).register(entries -> {
            entries.accept(Items.ITEM_TOMATO);
            entries.accept(Items.RAW_SHISH_KEBAB);
            entries.accept(Items.ITEM_SHISH_KEBAB);
            entries.accept(Items.ITEM_YOGHURT);
            entries.accept(Items.ITEM_HONEYBERRY_YOGHURT);
            entries.accept(Items.ITEM_HONEY_CUPCAKE);
            entries.accept(Items.ITEM_DONER_WRAP);
            entries.accept(Items.ITEM_CHUBBY_DONER);
            entries.accept(Items.ITEM_ALEXANDER);
            entries.accept(Items.ITEM_AYRAN);
            entries.accept(Items.DONER_SLICE);
            entries.accept(Items.BAKED_RICE_PUDDING);
            entries.accept(Items.SWEET_BERRY_JUICE);
            entries.accept(Items.RICE_PUDDING);
            entries.accept(Items.SWEET_BERRY_CUPCAKE_FANCY);
            entries.accept(Items.SWEET_BERRY_CUPCAKE);
            entries.accept(Items.ENDER_CUPCAKE);
            entries.accept(Items.SASHIMI);
            entries.accept(Items.OYAKODON);
            entries.accept(Items.BEEF_DONBURI);
            entries.accept(Items.EGG_SUSHI);
            entries.accept(Items.NIGIRI_SUSHI);
            entries.accept(Items.OMURICE);
            entries.accept(Items.SAKE);
            entries.accept(Items.RICEBALL);
            entries.accept(Items.SUSHI);
            entries.accept(Items.COOKED_RICE);
            entries.accept(Items.COLA);
            entries.accept(Items.ITEM_APPLE_CUPCAKE);
            entries.accept(Items.ITEM_PUMPKIN_CUPCAKE);
            entries.accept(Items.ITEM_COCOA_CUPCAKE);
            entries.accept(Items.ITEM_MELON_CUPCAKE);
            entries.accept(Items.ITEM_CARROT_CUPCAKE);
            entries.accept(Items.ITEM_FANCY_APPLE_CUPCAKE);
            entries.accept(Items.ITEM_FANCY_PUMPKIN_CUPCAKE);
            entries.accept(Items.GLOWBERRY_CUPCAKE);
            entries.accept(Items.ITEM_DONUT);
            entries.accept(Items.ITEM_FANCY_DONUT);
            entries.accept(Items.ITEM_SPRINKLES);
            entries.accept(Items.ITEM_CHOCOLATE);
            entries.accept(Items.ITEM_BUN);
            entries.accept(Items.ITEM_RAW_PATTY);
            entries.accept(Items.ITEM_COOKED_PATTY);
            entries.accept(Items.ITEM_RAW_CHICKEN_PATTY);
            entries.accept(Items.ITEM_COOKED_CHICKEN_PATTY);
            entries.accept(Items.ITEM_HAMBURGER);
            entries.accept(Items.ITEM_CHICKEN_BURGER);
            entries.accept(Items.ITEM_MUSHROOM_BURGER);
            entries.accept(Items.ITEM_ULTIMATE_BOTTOM);
            entries.accept(Items.ITEM_ULTIMATE_TOP);
            entries.accept(Items.CHEESEBURGER);
            entries.accept(Items.COLA_EXTRACT);
            entries.accept(Items.COLA_POWDER);
            entries.accept(Items.CARBONATED_WATER);
            entries.accept(Items.ITEM_ULTIMATE_BURGER);
            entries.accept(Items.ITEM_ROTTEN_BURGER);
            entries.accept(Items.ITEM_COOKED_SAUSAGE);
            entries.accept(Items.ITEM_HOTDOG);
            entries.accept(Items.ITEM_FISH_BREAD);
            entries.accept(Items.ITEM_DAISY_SANDWICH);
            entries.accept(Items.ITEM_CHICKEN_WRAP);
            entries.accept(Items.ITEM_RAW_SCHNITZEL);
            entries.accept(Items.ITEM_COOKED_SCHNITZEL);
            entries.accept(Items.ITEM_FRIED_EGG);
            entries.accept(Items.ITEM_CROISSANT);
            entries.accept(Items.ITEM_POTATO_FRIES);
            entries.accept(Items.ITEM_ICE_TEA);
            entries.accept(Items.ITEM_APPLE_JUICE);
            entries.accept(Items.ITEM_CARROT_JUICE);
            entries.accept(Items.ITEM_MELON_JUICE);
            entries.accept(Items.ITEM_PUMPKIN_JUICE);
            entries.accept(Items.ITEM_TOMATO_JUICE);
            entries.accept(Items.ITEM_WHEAT_JUICE);
            entries.accept(Items.ITEM_GLASS_OF_MILK);
            entries.accept(Items.ITEM_GLASS_OF_WATER);
            entries.accept(Items.SODA);
            entries.accept(Items.CHEESE_TOAST);
            entries.accept(Items.SQUID_INK_PAELLA);
            entries.accept(Items.GLOW_SQUID_INK_PAELLA);
            entries.accept(Items.ITEM_APPLE_PIE);
            entries.accept(Items.SWEET_BERRY_PIE);
            entries.accept(Items.RAW_PIZZA);
            entries.accept(Items.PIZZA);
            entries.accept(Items.ITEM_TOMATO_SLICES);
            entries.accept(Items.ITEM_POTATO_SLICES);
            entries.accept(Items.ITEM_RAW_SAUSAGE);
            entries.accept(Items.CHEESE_WHEEL);
            entries.accept(Items.CHEESE_SLICE);
            entries.accept(Items.ITEM_TEA_LEAF);
            entries.accept(Items.ITEM_TEA_DRIED);
            entries.accept(Items.ITEM_FULL_TEACUP_0);
            entries.accept(Items.ITEM_HOT_TEAPOT_7);
        });
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.TOOLS_AND_UTILITIES).register(entries -> {
            entries.accept(Items.ITEM_KNIFE);
        });
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.INGREDIENTS).register(entries -> {
            entries.accept(Items.ITEM_GLASS);
            entries.accept(Items.ITEM_TEACUP);
            entries.accept(Items.ITEM_TEAPOT);
        });
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(entries -> {
            entries.accept(Items.ITEM_TOMATO_SEEDS);
            entries.accept(Items.ITEM_RICE_SEEDS);
            entries.accept(Items.ITEM_TEA_SEEDS);
        });
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.FUNCTIONAL_BLOCKS).register(entries -> {
            entries.accept(Items.VAT);
        });

        registerItem("item_knife", ITEM_KNIFE);
        registerItem("item_glass", ITEM_GLASS);
        registerItem("ender_cupcake", ENDER_CUPCAKE);
        registerItem("cola_extract", COLA_EXTRACT);
        registerItem("cola_powder", COLA_POWDER);
        registerItem("item_ultimate_burger", ITEM_ULTIMATE_BURGER);
        registerItem("item_glass_of_water", ITEM_GLASS_OF_WATER);
        registerItem("item_apple_pie", ITEM_APPLE_PIE);
        registerItem("sweet_berry_pie", SWEET_BERRY_PIE);
        registerItem("item_teacup", ITEM_TEACUP);
        registerItem("item_full_teacup_0", ITEM_FULL_TEACUP_0);
        registerItem("item_full_teacup_1", ITEM_FULL_TEACUP_1);
        registerItem("item_full_teacup_2", ITEM_FULL_TEACUP_2);
        registerItem("item_full_teacup_3", ITEM_FULL_TEACUP_3);
        registerItem("item_full_teacup_4", ITEM_FULL_TEACUP_4);
        registerItem("item_full_teacup_5", ITEM_FULL_TEACUP_5);
        registerItem("item_full_teacup_6", ITEM_FULL_TEACUP_6);
        registerItem("item_full_teapot_0", ITEM_FULL_TEAPOT_0);
        registerItem("item_full_teapot_1", ITEM_FULL_TEAPOT_1);
        registerItem("item_full_teapot_2", ITEM_FULL_TEAPOT_2);
        registerItem("item_full_teapot_3", ITEM_FULL_TEAPOT_3);
        registerItem("item_full_teapot_4", ITEM_FULL_TEAPOT_4);
        registerItem("item_full_teapot_5", ITEM_FULL_TEAPOT_5);
        registerItem("item_full_teapot_6", ITEM_FULL_TEAPOT_6);
        registerItem("item_full_teapot_7", ITEM_FULL_TEAPOT_7);
        registerItem("item_hot_teapot_0", ITEM_HOT_TEAPOT_0);
        registerItem("item_hot_teapot_1", ITEM_HOT_TEAPOT_1);
        registerItem("item_hot_teapot_2", ITEM_HOT_TEAPOT_2);
        registerItem("item_hot_teapot_3", ITEM_HOT_TEAPOT_3);
        registerItem("item_hot_teapot_4", ITEM_HOT_TEAPOT_4);
        registerItem("item_hot_teapot_5", ITEM_HOT_TEAPOT_5);
        registerItem("item_hot_teapot_6", ITEM_HOT_TEAPOT_6);
        registerItem("item_hot_teapot_7", ITEM_HOT_TEAPOT_7);
        registerItem("item_teapot", ITEM_TEAPOT);
        registerItem("item_tea_seeds", ITEM_TEA_SEEDS);
        registerItem("item_tea_dried", ITEM_TEA_DRIED);
        registerItem("item_tea_leaf", ITEM_TEA_LEAF);
        registerItem("item_golden_cupcake", ITEM_GOLDEN_CUPCAKE);
        registerItem("item_tomato", ITEM_TOMATO);
        registerItem("item_tomato_seeds", ITEM_TOMATO_SEEDS);
        registerItem("item_rice_seeds", ITEM_RICE_SEEDS);
        registerItem("vat", VAT);
        registerItem("cheese_wheel", CHEESE_WHEEL);
        registerItem("item_apple_cupcake", ITEM_APPLE_CUPCAKE);
        registerItem("item_pumpkin_cupcake", ITEM_PUMPKIN_CUPCAKE);
        registerItem("item_cocoa_cupcake", ITEM_COCOA_CUPCAKE);
        registerItem("item_melon_cupcake", ITEM_MELON_CUPCAKE);
        registerItem("item_carrot_cupcake", ITEM_CARROT_CUPCAKE);
        registerItem("item_fancy_apple_cupcake", ITEM_FANCY_APPLE_CUPCAKE);
        registerItem("item_fancy_pumpkin_cupcake", ITEM_FANCY_PUMPKIN_CUPCAKE);
        registerItem("glowberry_cupcake", GLOWBERRY_CUPCAKE);
        registerItem("item_donut", ITEM_DONUT);
        registerItem("item_fancy_donut", ITEM_FANCY_DONUT);
        registerItem("item_sprinkles", ITEM_SPRINKLES);
        registerItem("item_chocolate", ITEM_CHOCOLATE);
        registerItem("item_bun", ITEM_BUN);
        registerItem("item_raw_patty", ITEM_RAW_PATTY);
        registerItem("item_cooked_patty", ITEM_COOKED_PATTY);
        registerItem("item_raw_chicken_patty", ITEM_RAW_CHICKEN_PATTY);
        registerItem("item_cooked_chicken_patty", ITEM_COOKED_CHICKEN_PATTY);
        registerItem("item_hamburger", ITEM_HAMBURGER);
        registerItem("item_chicken_burger", ITEM_CHICKEN_BURGER);
        registerItem("item_mushroom_burger", ITEM_MUSHROOM_BURGER);
        registerItem("item_ultimate_bottom", ITEM_ULTIMATE_BOTTOM);
        registerItem("item_ultimate_top", ITEM_ULTIMATE_TOP);
        registerItem("cheeseburger", CHEESEBURGER);
        registerItem("item_rotten_burger", ITEM_ROTTEN_BURGER);
        registerItem("item_raw_sausage", ITEM_RAW_SAUSAGE);
        registerItem("item_cooked_sausage", ITEM_COOKED_SAUSAGE);
        registerItem("item_hotdog", ITEM_HOTDOG);
        registerItem("item_fish_bread", ITEM_FISH_BREAD);
        registerItem("item_daisy_sandwich", ITEM_DAISY_SANDWICH);
        registerItem("item_chicken_wrap", ITEM_CHICKEN_WRAP);
        registerItem("item_raw_schnitzel", ITEM_RAW_SCHNITZEL);
        registerItem("item_cooked_schnitzel", ITEM_COOKED_SCHNITZEL);
        registerItem("item_fried_egg", ITEM_FRIED_EGG);
        registerItem("item_croissant", ITEM_CROISSANT);
        registerItem("item_potato_slices", ITEM_POTATO_SLICES);
        registerItem("item_potato_fries", ITEM_POTATO_FRIES);
        registerItem("item_shish_kebab", ITEM_SHISH_KEBAB);
        registerItem("item_tomato_slices", ITEM_TOMATO_SLICES);
        registerItem("item_ice_tea", ITEM_ICE_TEA);
        registerItem("item_apple_juice", ITEM_APPLE_JUICE);
        registerItem("item_carrot_juice", ITEM_CARROT_JUICE);
        registerItem("item_melon_juice", ITEM_MELON_JUICE);
        registerItem("item_pumpkin_juice", ITEM_PUMPKIN_JUICE);
        registerItem("item_tomato_juice", ITEM_TOMATO_JUICE);
        registerItem("item_wheat_juice", ITEM_WHEAT_JUICE);
        registerItem("item_glass_of_milk", ITEM_GLASS_OF_MILK);
        registerItem("sweet_berry_juice", SWEET_BERRY_JUICE);
        registerItem("item_ayran", ITEM_AYRAN);
        registerItem("sake", SAKE);
        registerItem("carbonated_water", CARBONATED_WATER);
        registerItem("soda", SODA);
        registerItem("cola", COLA);
        registerItem("oyakodon", OYAKODON);
        registerItem("beef_donburi", BEEF_DONBURI);
        registerItem("egg_sushi", EGG_SUSHI);
        registerItem("nigiri_sushi", NIGIRI_SUSHI);
        registerItem("omurice", OMURICE);
        registerItem("riceball", RICEBALL);
        registerItem("sushi", SUSHI);
        registerItem("cooked_rice", COOKED_RICE);
        registerItem("sashimi", SASHIMI);
        registerItem("rice_pudding", RICE_PUDDING);
        registerItem("baked_rice_pudding", BAKED_RICE_PUDDING);
        registerItem("sweet_berry_cupcake_fancy", SWEET_BERRY_CUPCAKE_FANCY);
        registerItem("sweet_berry_cupcake", SWEET_BERRY_CUPCAKE);
        registerItem("doner_slice", DONER_SLICE);
        registerItem("item_yoghurt", ITEM_YOGHURT);
        registerItem("item_honeyberry_yoghurt", ITEM_HONEYBERRY_YOGHURT);
        registerItem("item_honey_cupcake", ITEM_HONEY_CUPCAKE);
        registerItem("item_doner_wrap", ITEM_DONER_WRAP);
        registerItem("item_chubby_doner", ITEM_CHUBBY_DONER);
        registerItem("item_alexander", ITEM_ALEXANDER);
        registerItem("raw_shish_kebab", RAW_SHISH_KEBAB);
        registerItem("cheese_slice", CHEESE_SLICE);
        registerItem("cheese_toast", CHEESE_TOAST);
        registerItem("squid_ink_paella", SQUID_INK_PAELLA);
        registerItem("glow_squid_ink_paella", GLOW_SQUID_INK_PAELLA);
        registerItem("raw_pizza_pepperoni_pepperoni_pepperoni", RAW_PIZZA_PEPPERONI_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_mushroom_pepperoni_pepperoni", RAW_PIZZA_MUSHROOM_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_mushroom_mushroom_pepperoni", RAW_PIZZA_MUSHROOM_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_mushroom_mushroom_mushroom", RAW_PIZZA_MUSHROOM_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_meat_pepperoni_pepperoni", RAW_PIZZA_MEAT_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_meat_mushroom_pepperoni", RAW_PIZZA_MEAT_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_meat_mushroom_mushroom", RAW_PIZZA_MEAT_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_meat_meat_pepperoni", RAW_PIZZA_MEAT_MEAT_PEPPERONI);
        registerItem("raw_pizza_meat_meat_mushroom", RAW_PIZZA_MEAT_MEAT_MUSHROOM);
        registerItem("raw_pizza_meat_meat_meat", RAW_PIZZA_MEAT_MEAT_MEAT);
        registerItem("raw_pizza_fish_pepperoni_pepperoni", RAW_PIZZA_FISH_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_fish_mushroom_pepperoni", RAW_PIZZA_FISH_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_fish_mushroom_mushroom", RAW_PIZZA_FISH_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_fish_meat_pepperoni", RAW_PIZZA_FISH_MEAT_PEPPERONI);
        registerItem("raw_pizza_fish_meat_mushroom", RAW_PIZZA_FISH_MEAT_MUSHROOM);
        registerItem("raw_pizza_fish_meat_meat", RAW_PIZZA_FISH_MEAT_MEAT);
        registerItem("raw_pizza_fish_fish_pepperoni", RAW_PIZZA_FISH_FISH_PEPPERONI);
        registerItem("raw_pizza_fish_fish_mushroom", RAW_PIZZA_FISH_FISH_MUSHROOM);
        registerItem("raw_pizza_fish_fish_meat", RAW_PIZZA_FISH_FISH_MEAT);
        registerItem("raw_pizza_fish_fish_fish", RAW_PIZZA_FISH_FISH_FISH);
        registerItem("raw_pizza_chicken_pepperoni_pepperoni", RAW_PIZZA_CHICKEN_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_chicken_mushroom_pepperoni", RAW_PIZZA_CHICKEN_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_chicken_mushroom_mushroom", RAW_PIZZA_CHICKEN_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_chicken_meat_pepperoni", RAW_PIZZA_CHICKEN_MEAT_PEPPERONI);
        registerItem("raw_pizza_chicken_meat_mushroom", RAW_PIZZA_CHICKEN_MEAT_MUSHROOM);
        registerItem("raw_pizza_chicken_meat_meat", RAW_PIZZA_CHICKEN_MEAT_MEAT);
        registerItem("raw_pizza_chicken_fish_pepperoni", RAW_PIZZA_CHICKEN_FISH_PEPPERONI);
        registerItem("raw_pizza_chicken_fish_mushroom", RAW_PIZZA_CHICKEN_FISH_MUSHROOM);
        registerItem("raw_pizza_chicken_fish_meat", RAW_PIZZA_CHICKEN_FISH_MEAT);
        registerItem("raw_pizza_chicken_fish_fish", RAW_PIZZA_CHICKEN_FISH_FISH);
        registerItem("raw_pizza_chicken_chicken_pepperoni", RAW_PIZZA_CHICKEN_CHICKEN_PEPPERONI);
        registerItem("raw_pizza_chicken_chicken_mushroom", RAW_PIZZA_CHICKEN_CHICKEN_MUSHROOM);
        registerItem("raw_pizza_chicken_chicken_meat", RAW_PIZZA_CHICKEN_CHICKEN_MEAT);
        registerItem("raw_pizza_chicken_chicken_fish", RAW_PIZZA_CHICKEN_CHICKEN_FISH);
        registerItem("raw_pizza_chicken_chicken_chicken", RAW_PIZZA_CHICKEN_CHICKEN_CHICKEN);
        registerItem("raw_pizza_pepperoni_pepperoni", RAW_PIZZA_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_mushroom_pepperoni", RAW_PIZZA_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_mushroom_mushroom", RAW_PIZZA_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_meat_pepperoni", RAW_PIZZA_MEAT_PEPPERONI);
        registerItem("raw_pizza_meat_mushroom", RAW_PIZZA_MEAT_MUSHROOM);
        registerItem("raw_pizza_meat_meat", RAW_PIZZA_MEAT_MEAT);
        registerItem("raw_pizza_fish_pepperoni", RAW_PIZZA_FISH_PEPPERONI);
        registerItem("raw_pizza_fish_mushroom", RAW_PIZZA_FISH_MUSHROOM);
        registerItem("raw_pizza_fish_meat", RAW_PIZZA_FISH_MEAT);
        registerItem("raw_pizza_fish_fish", RAW_PIZZA_FISH_FISH);
        registerItem("raw_pizza_chicken_pepperoni", RAW_PIZZA_CHICKEN_PEPPERONI);
        registerItem("raw_pizza_chicken_mushroom", RAW_PIZZA_CHICKEN_MUSHROOM);
        registerItem("raw_pizza_chicken_meat", RAW_PIZZA_CHICKEN_MEAT);
        registerItem("raw_pizza_chicken_fish", RAW_PIZZA_CHICKEN_FISH);
        registerItem("raw_pizza_chicken_chicken", RAW_PIZZA_CHICKEN_CHICKEN);
        registerItem("raw_pizza_pepperoni", RAW_PIZZA_PEPPERONI);
        registerItem("raw_pizza_mushroom", RAW_PIZZA_MUSHROOM);
        registerItem("raw_pizza_meat", RAW_PIZZA_MEAT);
        registerItem("raw_pizza_fish", RAW_PIZZA_FISH);
        registerItem("raw_pizza_chicken", RAW_PIZZA_CHICKEN);
        registerItem("raw_pizza", RAW_PIZZA);
        registerItem("pizza_pepperoni_pepperoni_pepperoni", PIZZA_PEPPERONI_PEPPERONI_PEPPERONI);
        registerItem("pizza_mushroom_pepperoni_pepperoni", PIZZA_MUSHROOM_PEPPERONI_PEPPERONI);
        registerItem("pizza_mushroom_mushroom_pepperoni", PIZZA_MUSHROOM_MUSHROOM_PEPPERONI);
        registerItem("pizza_mushroom_mushroom_mushroom", PIZZA_MUSHROOM_MUSHROOM_MUSHROOM);
        registerItem("pizza_meat_pepperoni_pepperoni", PIZZA_MEAT_PEPPERONI_PEPPERONI);
        registerItem("pizza_meat_mushroom_pepperoni", PIZZA_MEAT_MUSHROOM_PEPPERONI);
        registerItem("pizza_meat_mushroom_mushroom", PIZZA_MEAT_MUSHROOM_MUSHROOM);
        registerItem("pizza_meat_meat_pepperoni", PIZZA_MEAT_MEAT_PEPPERONI);
        registerItem("pizza_meat_meat_mushroom", PIZZA_MEAT_MEAT_MUSHROOM);
        registerItem("pizza_meat_meat_meat", PIZZA_MEAT_MEAT_MEAT);
        registerItem("pizza_fish_pepperoni_pepperoni", PIZZA_FISH_PEPPERONI_PEPPERONI);
        registerItem("pizza_fish_mushroom_pepperoni", PIZZA_FISH_MUSHROOM_PEPPERONI);
        registerItem("pizza_fish_mushroom_mushroom", PIZZA_FISH_MUSHROOM_MUSHROOM);
        registerItem("pizza_fish_meat_pepperoni", PIZZA_FISH_MEAT_PEPPERONI);
        registerItem("pizza_fish_meat_mushroom", PIZZA_FISH_MEAT_MUSHROOM);
        registerItem("pizza_fish_meat_meat", PIZZA_FISH_MEAT_MEAT);
        registerItem("pizza_fish_fish_pepperoni", PIZZA_FISH_FISH_PEPPERONI);
        registerItem("pizza_fish_fish_mushroom", PIZZA_FISH_FISH_MUSHROOM);
        registerItem("pizza_fish_fish_meat", PIZZA_FISH_FISH_MEAT);
        registerItem("pizza_fish_fish_fish", PIZZA_FISH_FISH_FISH);
        registerItem("pizza_chicken_pepperoni_pepperoni", PIZZA_CHICKEN_PEPPERONI_PEPPERONI);
        registerItem("pizza_chicken_mushroom_pepperoni", PIZZA_CHICKEN_MUSHROOM_PEPPERONI);
        registerItem("pizza_chicken_mushroom_mushroom", PIZZA_CHICKEN_MUSHROOM_MUSHROOM);
        registerItem("pizza_chicken_meat_pepperoni", PIZZA_CHICKEN_MEAT_PEPPERONI);
        registerItem("pizza_chicken_meat_mushroom", PIZZA_CHICKEN_MEAT_MUSHROOM);
        registerItem("pizza_chicken_meat_meat", PIZZA_CHICKEN_MEAT_MEAT);
        registerItem("pizza_chicken_fish_pepperoni", PIZZA_CHICKEN_FISH_PEPPERONI);
        registerItem("pizza_chicken_fish_mushroom", PIZZA_CHICKEN_FISH_MUSHROOM);
        registerItem("pizza_chicken_fish_meat", PIZZA_CHICKEN_FISH_MEAT);
        registerItem("pizza_chicken_fish_fish", PIZZA_CHICKEN_FISH_FISH);
        registerItem("pizza_chicken_chicken_pepperoni", PIZZA_CHICKEN_CHICKEN_PEPPERONI);
        registerItem("pizza_chicken_chicken_mushroom", PIZZA_CHICKEN_CHICKEN_MUSHROOM);
        registerItem("pizza_chicken_chicken_meat", PIZZA_CHICKEN_CHICKEN_MEAT);
        registerItem("pizza_chicken_chicken_fish", PIZZA_CHICKEN_CHICKEN_FISH);
        registerItem("pizza_chicken_chicken_chicken", PIZZA_CHICKEN_CHICKEN_CHICKEN);
        registerItem("pizza_pepperoni_pepperoni", PIZZA_PEPPERONI_PEPPERONI);
        registerItem("pizza_mushroom_pepperoni", PIZZA_MUSHROOM_PEPPERONI);
        registerItem("pizza_mushroom_mushroom", PIZZA_MUSHROOM_MUSHROOM);
        registerItem("pizza_meat_pepperoni", PIZZA_MEAT_PEPPERONI);
        registerItem("pizza_meat_mushroom", PIZZA_MEAT_MUSHROOM);
        registerItem("pizza_meat_meat", PIZZA_MEAT_MEAT);
        registerItem("pizza_fish_pepperoni", PIZZA_FISH_PEPPERONI);
        registerItem("pizza_fish_mushroom", PIZZA_FISH_MUSHROOM);
        registerItem("pizza_fish_meat", PIZZA_FISH_MEAT);
        registerItem("pizza_fish_fish", PIZZA_FISH_FISH);
        registerItem("pizza_chicken_pepperoni", PIZZA_CHICKEN_PEPPERONI);
        registerItem("pizza_chicken_mushroom", PIZZA_CHICKEN_MUSHROOM);
        registerItem("pizza_chicken_meat", PIZZA_CHICKEN_MEAT);
        registerItem("pizza_chicken_fish", PIZZA_CHICKEN_FISH);
        registerItem("pizza_chicken_chicken", PIZZA_CHICKEN_CHICKEN);
        registerItem("pizza_pepperoni", PIZZA_PEPPERONI);
        registerItem("pizza_mushroom", PIZZA_MUSHROOM);
        registerItem("pizza_meat", PIZZA_MEAT);
        registerItem("pizza_fish", PIZZA_FISH);
        registerItem("pizza_chicken", PIZZA_CHICKEN);
        registerItem("pizza", PIZZA);
    }
}