package xerca.xercafood.common.item;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.item.crafting.SimpleCraftingRecipeSerializer;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.ComposterBlock;
import xerca.xercafood.common.Mod;
import xerca.xercafood.common.block.BlockPizza;
import xerca.xercafood.common.block.Blocks;
import xerca.xercafood.common.crafting.RecipeTeaFilling;
import xerca.xercafood.common.crafting.RecipeTeaPouring;
import xerca.xercafood.common.crafting.RecipeTeaRefilling;
import xerca.xercafood.common.crafting.RecipeTeaSugaring;

public final class Items {
    private static final boolean REGISTER_LOCAL_KNIFE = !FabricLoader.getInstance().isModLoaded("xercatools");
    public static final Item KNIFE = new ItemKnife();
    public static final Item GLASS = new ItemGlass();
    public static final Item ENDER_CUPCAKE = new ItemEnderCupcake();
    public static final Item COLA_EXTRACT = new Item(new Item.Properties().craftRemainder(net.minecraft.world.item.Items.GLASS_BOTTLE));
    public static final Item COLA_POWDER = new Item(new Item.Properties());
    public static final Item ULTIMATE_BURGER = new ItemUltimateBurger();
    public static final Item GLASS_OF_WATER = new ItemGlassOfWater(new Item.Properties().food(Foods.GLASS_OF_WATER), GLASS);
    public static final Item APPLE_PIE = new BlockItem(Blocks.BLOCK_APPLE_PIE, new Item.Properties());
    public static final Item SWEET_BERRY_PIE = new BlockItem(Blocks.BLOCK_SWEET_BERRY_PIE, new Item.Properties());
    public static final Item TEACUP = new ItemTea(new Item.Properties());
    public static final ItemTeacup FULL_TEACUP_0 = new ItemTeacup(0, TEACUP);
    public static final ItemTeacup FULL_TEACUP_1 = new ItemTeacup(1, TEACUP);
    public static final ItemTeacup FULL_TEACUP_2 = new ItemTeacup(2, TEACUP);
    public static final ItemTeacup FULL_TEACUP_3 = new ItemTeacup(3, TEACUP);
    public static final ItemTeacup FULL_TEACUP_4 = new ItemTeacup(4, TEACUP);
    public static final ItemTeacup FULL_TEACUP_5 = new ItemTeacup(5, TEACUP);
    public static final ItemTeacup FULL_TEACUP_6 = new ItemTeacup(6, TEACUP);
    public static final ItemTeapot FULL_TEAPOT_0 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 0, false);
    public static final ItemTeapot FULL_TEAPOT_1 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 1, false);
    public static final ItemTeapot FULL_TEAPOT_2 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 2, false);
    public static final ItemTeapot FULL_TEAPOT_3 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 3, false);
    public static final ItemTeapot FULL_TEAPOT_4 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 4, false);
    public static final ItemTeapot FULL_TEAPOT_5 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 5, false);
    public static final ItemTeapot FULL_TEAPOT_6 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 6, false);
    public static final ItemTeapot FULL_TEAPOT_7 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 7, false);
    public static final ItemTeapot HOT_TEAPOT_0 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 0, true);
    public static final ItemTeapot HOT_TEAPOT_1 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 1, true);
    public static final ItemTeapot HOT_TEAPOT_2 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 2, true);
    public static final ItemTeapot HOT_TEAPOT_3 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 3, true);
    public static final ItemTeapot HOT_TEAPOT_4 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 4, true);
    public static final ItemTeapot HOT_TEAPOT_5 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 5, true);
    public static final ItemTeapot HOT_TEAPOT_6 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 6, true);
    public static final ItemTeapot HOT_TEAPOT_7 = new ItemTeapot(Blocks.BLOCK_TEAPOT, 7, true);
    public static final ItemEmptyTeapot TEAPOT = new ItemEmptyTeapot(new Item.Properties());
    public static final Item TEA_SEEDS = new BlockItem(Blocks.BLOCK_TEA_PLANT, new Item.Properties());
    public static final Item TEA_DRIED = new ItemTea(new Item.Properties());
    public static final Item TEA_LEAF = new ItemTea(new Item.Properties());
    public static final ItemGoldenCupcake GOLDEN_CUPCAKE = new ItemGoldenCupcake();
    public static final ItemTomato TOMATO = new ItemTomato();
    public static final Item TOMATO_SEEDS = new BlockItem(Blocks.BLOCK_TOMATO_PLANT, new Item.Properties());
    public static final Item RICE_SEEDS = new BlockItem(Blocks.BLOCK_RICE_PLANT, new Item.Properties());
    public static final Item VAT = new BlockItem(Blocks.VAT, new Item.Properties());
    public static final Item CHEESE_WHEEL = new BlockItem(Blocks.CHEESE_WHEEL, new Item.Properties());
    public static final Item APPLE_CUPCAKE = makeFoodItem(Foods.APPLE_CUPCAKE);
    public static final Item PUMPKIN_CUPCAKE = makeFoodItem(Foods.PUMPKIN_CUPCAKE);
    public static final Item COCOA_CUPCAKE = makeFoodItem(Foods.COCOA_CUPCAKE);
    public static final Item MELON_CUPCAKE = makeFoodItem(Foods.MELON_CUPCAKE);
    public static final Item CARROT_CUPCAKE = makeFoodItem(Foods.CARROT_CUPCAKE);
    public static final Item FANCY_APPLE_CUPCAKE = makeFoodItem(Foods.FANCY_APPLE_CUPCAKE);
    public static final Item FANCY_PUMPKIN_CUPCAKE = makeFoodItem(Foods.FANCY_PUMPKIN_CUPCAKE);
    public static final Item GLOWBERRY_CUPCAKE = makeFoodItem(Foods.GLOWBERRY_CUPCAKE);
    public static final Item DONUT = makeFoodItem(Foods.DONUT);
    public static final Item FANCY_DONUT = makeFoodItem(Foods.FANCY_DONUT);
    public static final Item SPRINKLES = makeFoodItem(Foods.SPRINKLES);
    public static final Item CHOCOLATE = makeFoodItem(Foods.CHOCOLATE);
    public static final Item BUN = makeFoodItem(Foods.BUN);
    public static final Item RAW_PATTY = makeFoodItem(Foods.RAW_PATTY);
    public static final Item COOKED_PATTY = makeFoodItem(Foods.COOKED_PATTY);
    public static final Item RAW_CHICKEN_PATTY = makeFoodItem(Foods.RAW_CHICKEN_PATTY);
    public static final Item COOKED_CHICKEN_PATTY = makeFoodItem(Foods.COOKED_CHICKEN_PATTY);
    public static final Item HAMBURGER = makeFoodItem(Foods.HAMBURGER);
    public static final Item CHICKEN_BURGER = makeFoodItem(Foods.CHICKEN_BURGER);
    public static final Item MUSHROOM_BURGER = makeFoodItem(Foods.MUSHROOM_BURGER);
    public static final Item ULTIMATE_BOTTOM = makeFoodItem(Foods.ULTIMATE_BOTTOM);
    public static final Item ULTIMATE_TOP = makeFoodItem(Foods.ULTIMATE_TOP);
    public static final Item CHEESEBURGER = makeFoodItem(Foods.CHEESEBURGER);
    public static final Item ROTTEN_BURGER = makeFoodItem(Foods.ROTTEN_BURGER);
    public static final Item RAW_SAUSAGE = makeFoodItem(Foods.RAW_SAUSAGE);
    public static final Item COOKED_SAUSAGE = makeFoodItem(Foods.COOKED_SAUSAGE);
    public static final Item HOTDOG = makeFoodItem(Foods.HOTDOG);
    public static final Item FISH_BREAD = makeFoodItem(Foods.FISH_BREAD);
    public static final Item DAISY_SANDWICH = makeFoodItem(Foods.DAISY_SANDWICH);
    public static final Item CHICKEN_WRAP = makeFoodItem(Foods.CHICKEN_WRAP);
    public static final Item RAW_SCHNITZEL = makeFoodItem(Foods.RAW_SCHNITZEL);
    public static final Item COOKED_SCHNITZEL = makeFoodItem(Foods.COOKED_SCHNITZEL);
    public static final Item FRIED_EGG = makeFoodItem(Foods.FRIED_EGG);
    public static final Item CROISSANT = makeFoodItem(Foods.CROISSANT);
    public static final Item POTATO_SLICES = makeFoodItem(Foods.POTATO_SLICES);
    public static final Item POTATO_FRIES = makeFoodItem(Foods.POTATO_FRIES);
    public static final Item SHISH_KEBAB = makeFoodItem(Foods.SHISH_KEBAB);
    public static final Item TOMATO_SLICES = makeFoodItem(Foods.TOMATO_SLICES);
    public static final Item ICE_TEA = makeDrinkItem(Foods.ICE_TEA, GLASS);
    public static final Item APPLE_JUICE = makeDrinkItem(Foods.APPLE_JUICE, GLASS);
    public static final Item CARROT_JUICE = makeDrinkItem(Foods.CARROT_JUICE, GLASS);
    public static final Item MELON_JUICE = makeDrinkItem(Foods.MELON_JUICE, GLASS);
    public static final Item PUMPKIN_JUICE = makeDrinkItem(Foods.PUMPKIN_JUICE, GLASS);
    public static final Item TOMATO_JUICE = makeDrinkItem(Foods.TOMATO_JUICE, GLASS);
    public static final Item WHEAT_JUICE = makeDrinkItem(Foods.WHEAT_JUICE, GLASS);
    public static final Item GLASS_OF_MILK = makeDrinkItem(Foods.GLASS_OF_MILK, GLASS);
    public static final Item SWEET_BERRY_JUICE = makeDrinkItem(Foods.SWEET_BERRY_JUICE, GLASS);
    public static final Item AYRAN = makeDrinkItem(Foods.AYRAN, GLASS);
    public static final Item SAKE = makeDrinkItem(Foods.SAKE, GLASS);
    public static final Item CARBONATED_WATER = makeDrinkItem(Foods.CARBONATED_WATER, GLASS);
    public static final Item SODA = makeDrinkItem(Foods.SODA, GLASS);
    public static final Item COLA = makeDrinkItem(Foods.COLA, GLASS);
    public static final Item OYAKODON = makeContainedFoodItem(Foods.OYAKODON, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item BEEF_DONBURI = makeContainedFoodItem(Foods.BEEF_DONBURI, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item EGG_SUSHI = makeFoodItem(Foods.EGG_SUSHI);
    public static final Item NIGIRI_SUSHI = makeFoodItem(Foods.NIGIRI_SUSHI);
    public static final Item OMURICE = makeFoodItem(Foods.OMURICE);
    public static final Item RICEBALL = makeFoodItem(Foods.RICEBALL);
    public static final Item SUSHI = makeFoodItem(Foods.SUSHI);
    public static final Item COOKED_RICE = makeFoodItem(Foods.COOKED_RICE);
    public static final Item SASHIMI = makeFoodItem(Foods.SASHIMI);
    public static final Item RICE_PUDDING = makeContainedFoodItem(Foods.RICE_PUDDING, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item BAKED_RICE_PUDDING = makeContainedFoodItem(Foods.BAKED_RICE_PUDDING, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item SWEET_BERRY_CUPCAKE_FANCY = makeFoodItem(Foods.SWEET_BERRY_CUPCAKE_FANCY);
    public static final Item SWEET_BERRY_CUPCAKE = makeFoodItem(Foods.SWEET_BERRY_CUPCAKE);
    public static final Item DONER_SLICE = makeFoodItem(Foods.DONER_SLICE);
    public static final Item YOGHURT = makeContainedFoodItem(Foods.YOGHURT, net.minecraft.world.item.Items.BUCKET, 16);
    public static final Item HONEYBERRY_YOGHURT = makeContainedFoodItem(Foods.HONEYBERRY_YOGHURT, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item HONEY_CUPCAKE = makeFoodItem(Foods.HONEY_CUPCAKE);
    public static final Item DONER_WRAP = makeFoodItem(Foods.DONER_WRAP);
    public static final Item CHUBBY_DONER = makeFoodItem(Foods.CHUBBY_DONER);
    public static final Item ALEXANDER = makeContainedFoodItem(Foods.ALEXANDER, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item RAW_SHISH_KEBAB = makeFoodItem(Foods.RAW_SHISH_KEBAB);
    public static final Item CHEESE_SLICE = makeFoodItem(Foods.CHEESE_SLICE);
    public static final Item CHEESE_TOAST = makeFoodItem(Foods.CHEESE_TOAST);
    public static final Item SQUID_INK_PAELLA = makeContainedFoodItem(Foods.SQUID_INK_PAELLA, net.minecraft.world.item.Items.BOWL, 16);
    public static final Item GLOW_SQUID_INK_PAELLA = makeContainedFoodItem(Foods.GLOW_SQUID_INK_PAELLA, net.minecraft.world.item.Items.BOWL, 16);

    public static final Item RAW_PIZZA_PEPPERONI_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MUSHROOM_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MUSHROOM_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MUSHROOM_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MEAT_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MEAT_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_MEAT_MEAT_MEAT = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MEAT_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MEAT_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_MEAT_MEAT = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_FISH_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_FISH_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_FISH_MEAT = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_FISH_FISH_FISH = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MEAT_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MEAT_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_MEAT_MEAT = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_FISH_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_FISH_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_FISH_MEAT = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_FISH_FISH = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_MEAT = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_FISH = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN_CHICKEN = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, Foods.RAW_PIZZA_3);
    public static final Item RAW_PIZZA_PEPPERONI_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MUSHROOM_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MUSHROOM_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MEAT_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MEAT_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_MEAT_MEAT = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_FISH_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_FISH_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_FISH_MEAT = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_FISH_FISH = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_MEAT = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_FISH = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_CHICKEN_CHICKEN = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_2);
    public static final Item RAW_PIZZA_PEPPERONI = new ItemRawPizza(BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA_MUSHROOM = new ItemRawPizza(BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA_MEAT = new ItemRawPizza(BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA_FISH = new ItemRawPizza(BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA_CHICKEN = new ItemRawPizza(BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_1);
    public static final Item RAW_PIZZA = new ItemRawPizza(BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, Foods.RAW_PIZZA_0);
    public static final Item PIZZA_PEPPERONI_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_PEPPERONI_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MUSHROOM_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_MUSHROOM_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MUSHROOM_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_MUSHROOM_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MUSHROOM_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_MUSHROOM_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_MEAT_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_MEAT_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MEAT_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_MEAT_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MEAT_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_MEAT_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_MEAT_MEAT_PEPPERONI = new ItemPizza(Blocks.PIZZA_MEAT_MEAT_PEPPERONI, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_MEAT_MEAT_MUSHROOM = new ItemPizza(Blocks.PIZZA_MEAT_MEAT_MUSHROOM, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_MEAT_MEAT_MEAT = new ItemPizza(Blocks.PIZZA_MEAT_MEAT_MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_FISH_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_FISH_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_FISH_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_FISH_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_FISH_MEAT_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_MEAT_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_FISH_MEAT_MUSHROOM = new ItemPizza(Blocks.PIZZA_FISH_MEAT_MUSHROOM, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_FISH_MEAT_MEAT = new ItemPizza(Blocks.PIZZA_FISH_MEAT_MEAT, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_FISH_FISH_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_FISH_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_FISH_FISH_MUSHROOM = new ItemPizza(Blocks.PIZZA_FISH_FISH_MUSHROOM, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_FISH_FISH_MEAT = new ItemPizza(Blocks.PIZZA_FISH_FISH_MEAT, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_FISH_FISH_FISH = new ItemPizza(Blocks.PIZZA_FISH_FISH_FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH);
    public static final Item PIZZA_CHICKEN_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_CHICKEN_MEAT_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_MEAT_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_MEAT_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_MEAT_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_CHICKEN_MEAT_MEAT = new ItemPizza(Blocks.PIZZA_CHICKEN_MEAT_MEAT, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_CHICKEN_FISH_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_FISH_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_CHICKEN_FISH_MEAT = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH_MEAT, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_CHICKEN_FISH_FISH = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH_FISH, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH);
    public static final Item PIZZA_CHICKEN_CHICKEN_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI);
    public static final Item PIZZA_CHICKEN_CHICKEN_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM);
    public static final Item PIZZA_CHICKEN_CHICKEN_MEAT = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_MEAT, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT);
    public static final Item PIZZA_CHICKEN_CHICKEN_FISH = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_FISH, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH);
    public static final Item PIZZA_CHICKEN_CHICKEN_CHICKEN = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN_CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN);
    public static final Item PIZZA_PEPPERONI_PEPPERONI = new ItemPizza(Blocks.PIZZA_PEPPERONI_PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MUSHROOM_PEPPERONI = new ItemPizza(Blocks.PIZZA_MUSHROOM_PEPPERONI, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MUSHROOM_MUSHROOM = new ItemPizza(Blocks.PIZZA_MUSHROOM_MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MEAT_PEPPERONI = new ItemPizza(Blocks.PIZZA_MEAT_PEPPERONI, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MEAT_MUSHROOM = new ItemPizza(Blocks.PIZZA_MEAT_MUSHROOM, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MEAT_MEAT = new ItemPizza(Blocks.PIZZA_MEAT_MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH_PEPPERONI = new ItemPizza(Blocks.PIZZA_FISH_PEPPERONI, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH_MUSHROOM = new ItemPizza(Blocks.PIZZA_FISH_MUSHROOM, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH_MEAT = new ItemPizza(Blocks.PIZZA_FISH_MEAT, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH_FISH = new ItemPizza(Blocks.PIZZA_FISH_FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_PEPPERONI = new ItemPizza(Blocks.PIZZA_CHICKEN_PEPPERONI, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_MUSHROOM = new ItemPizza(Blocks.PIZZA_CHICKEN_MUSHROOM, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_MEAT = new ItemPizza(Blocks.PIZZA_CHICKEN_MEAT, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_FISH = new ItemPizza(Blocks.PIZZA_CHICKEN_FISH, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN_CHICKEN = new ItemPizza(Blocks.PIZZA_CHICKEN_CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_PEPPERONI = new ItemPizza(Blocks.PIZZA_PEPPERONI, BlockPizza.Ingredient.PEPPERONI, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MUSHROOM = new ItemPizza(Blocks.PIZZA_MUSHROOM, BlockPizza.Ingredient.MUSHROOM, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_MEAT = new ItemPizza(Blocks.PIZZA_MEAT, BlockPizza.Ingredient.MEAT, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_FISH = new ItemPizza(Blocks.PIZZA_FISH, BlockPizza.Ingredient.FISH, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA_CHICKEN = new ItemPizza(Blocks.PIZZA_CHICKEN, BlockPizza.Ingredient.CHICKEN, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);
    public static final Item PIZZA = new ItemPizza(Blocks.PIZZA, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY, BlockPizza.Ingredient.EMPTY);

    public static final RecipeSerializer<RecipeTeaSugaring> CRAFTING_SPECIAL_TEA_SUGARING = new SimpleCraftingRecipeSerializer<>(RecipeTeaSugaring::new);
    public static final RecipeSerializer<RecipeTeaPouring> CRAFTING_SPECIAL_TEA_POURING = new SimpleCraftingRecipeSerializer<>(RecipeTeaPouring::new);
    public static final RecipeSerializer<RecipeTeaFilling> CRAFTING_SPECIAL_TEA_FILLING = new SimpleCraftingRecipeSerializer<>(RecipeTeaFilling::new);
    public static final RecipeSerializer<RecipeTeaRefilling> CRAFTING_SPECIAL_TEA_REFILLING = new SimpleCraftingRecipeSerializer<>(RecipeTeaRefilling::new);

    static Item makeFoodItem(FoodProperties food) {
        return new Item(new Item.Properties().food(food));
    }

    static Item makeContainedFoodItem(FoodProperties food, Item container, int stackSize) {
        return new ItemStackableContainedFood(new Item.Properties().food(food).
                craftRemainder(container), container, stackSize);
    }

    static Item makeDrinkItem(FoodProperties food, Item container) {
        return new ItemDrink(new Item.Properties().food(food), container);
    }

    private static void registerItem(String name, Item item) {
        Registry.register(BuiltInRegistries.ITEM, Mod.id(name), item);
    }

    static void registerCompostable(float chance, ItemLike itemIn) {
        ComposterBlock.COMPOSTABLES.put(itemIn.asItem(), chance);
    }

    public static void registerCompostables() {
        registerCompostable(0.3f, TEA_SEEDS);
        registerCompostable(0.3f, TOMATO_SEEDS);
        registerCompostable(0.3f, RICE_SEEDS);
        registerCompostable(0.65f, TOMATO);
        registerCompostable(0.65f, TEA_DRIED);
        registerCompostable(0.65f, TEA_LEAF);
    }

    public static void registerRecipes() {
        Registry.register(BuiltInRegistries.RECIPE_SERIALIZER, Mod.id("crafting_special_tea_sugaring"), CRAFTING_SPECIAL_TEA_SUGARING);
        Registry.register(BuiltInRegistries.RECIPE_SERIALIZER, Mod.id("crafting_special_tea_pouring"), CRAFTING_SPECIAL_TEA_POURING);
        Registry.register(BuiltInRegistries.RECIPE_SERIALIZER, Mod.id("crafting_special_tea_filling"), CRAFTING_SPECIAL_TEA_FILLING);
        Registry.register(BuiltInRegistries.RECIPE_SERIALIZER, Mod.id("crafting_special_tea_refilling"), CRAFTING_SPECIAL_TEA_REFILLING);
    }

    public static void registerItems() {
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.FOOD_AND_DRINKS).register(entries -> {
            entries.accept(Items.TOMATO);
            entries.accept(Items.RAW_SHISH_KEBAB);
            entries.accept(Items.SHISH_KEBAB);
            entries.accept(Items.YOGHURT);
            entries.accept(Items.HONEYBERRY_YOGHURT);
            entries.accept(Items.HONEY_CUPCAKE);
            entries.accept(Items.DONER_WRAP);
            entries.accept(Items.CHUBBY_DONER);
            entries.accept(Items.ALEXANDER);
            entries.accept(Items.AYRAN);
            entries.accept(Items.DONER_SLICE);
            entries.accept(Items.BAKED_RICE_PUDDING);
            entries.accept(Items.SWEET_BERRY_JUICE);
            entries.accept(Items.RICE_PUDDING);
            entries.accept(Items.SWEET_BERRY_CUPCAKE_FANCY);
            entries.accept(Items.SWEET_BERRY_CUPCAKE);
            entries.accept(Items.ENDER_CUPCAKE);
            entries.accept(Items.SASHIMI);
            entries.accept(Items.OYAKODON);
            entries.accept(Items.BEEF_DONBURI);
            entries.accept(Items.EGG_SUSHI);
            entries.accept(Items.NIGIRI_SUSHI);
            entries.accept(Items.OMURICE);
            entries.accept(Items.SAKE);
            entries.accept(Items.RICEBALL);
            entries.accept(Items.SUSHI);
            entries.accept(Items.COOKED_RICE);
            entries.accept(Items.COLA);
            entries.accept(Items.APPLE_CUPCAKE);
            entries.accept(Items.PUMPKIN_CUPCAKE);
            entries.accept(Items.COCOA_CUPCAKE);
            entries.accept(Items.MELON_CUPCAKE);
            entries.accept(Items.CARROT_CUPCAKE);
            entries.accept(Items.FANCY_APPLE_CUPCAKE);
            entries.accept(Items.FANCY_PUMPKIN_CUPCAKE);
            entries.accept(Items.GLOWBERRY_CUPCAKE);
            entries.accept(Items.DONUT);
            entries.accept(Items.FANCY_DONUT);
            entries.accept(Items.SPRINKLES);
            entries.accept(Items.CHOCOLATE);
            entries.accept(Items.BUN);
            entries.accept(Items.RAW_PATTY);
            entries.accept(Items.COOKED_PATTY);
            entries.accept(Items.RAW_CHICKEN_PATTY);
            entries.accept(Items.COOKED_CHICKEN_PATTY);
            entries.accept(Items.HAMBURGER);
            entries.accept(Items.CHICKEN_BURGER);
            entries.accept(Items.MUSHROOM_BURGER);
            entries.accept(Items.ULTIMATE_BOTTOM);
            entries.accept(Items.ULTIMATE_TOP);
            entries.accept(Items.CHEESEBURGER);
            entries.accept(Items.COLA_EXTRACT);
            entries.accept(Items.COLA_POWDER);
            entries.accept(Items.CARBONATED_WATER);
            entries.accept(Items.ULTIMATE_BURGER);
            entries.accept(Items.ROTTEN_BURGER);
            entries.accept(Items.COOKED_SAUSAGE);
            entries.accept(Items.HOTDOG);
            entries.accept(Items.FISH_BREAD);
            entries.accept(Items.DAISY_SANDWICH);
            entries.accept(Items.CHICKEN_WRAP);
            entries.accept(Items.RAW_SCHNITZEL);
            entries.accept(Items.COOKED_SCHNITZEL);
            entries.accept(Items.FRIED_EGG);
            entries.accept(Items.CROISSANT);
            entries.accept(Items.POTATO_FRIES);
            entries.accept(Items.ICE_TEA);
            entries.accept(Items.APPLE_JUICE);
            entries.accept(Items.CARROT_JUICE);
            entries.accept(Items.MELON_JUICE);
            entries.accept(Items.PUMPKIN_JUICE);
            entries.accept(Items.TOMATO_JUICE);
            entries.accept(Items.WHEAT_JUICE);
            entries.accept(Items.GLASS_OF_MILK);
            entries.accept(Items.GLASS_OF_WATER);
            entries.accept(Items.SODA);
            entries.accept(Items.CHEESE_TOAST);
            entries.accept(Items.SQUID_INK_PAELLA);
            entries.accept(Items.GLOW_SQUID_INK_PAELLA);
            entries.accept(Items.APPLE_PIE);
            entries.accept(Items.SWEET_BERRY_PIE);
            entries.accept(Items.RAW_PIZZA);
            entries.accept(Items.PIZZA);
            entries.accept(Items.TOMATO_SLICES);
            entries.accept(Items.POTATO_SLICES);
            entries.accept(Items.RAW_SAUSAGE);
            entries.accept(Items.CHEESE_WHEEL);
            entries.accept(Items.CHEESE_SLICE);
            entries.accept(Items.TEA_LEAF);
            entries.accept(Items.TEA_DRIED);
            entries.accept(Items.FULL_TEACUP_0);
            entries.accept(Items.HOT_TEAPOT_7);
        });
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.TOOLS_AND_UTILITIES).register(entries -> {
            if (REGISTER_LOCAL_KNIFE) {
                entries.accept(Items.KNIFE);
            }
        });
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.INGREDIENTS).register(entries -> {
            entries.accept(Items.GLASS);
            entries.accept(Items.TEACUP);
            entries.accept(Items.TEAPOT);
        });
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.NATURAL_BLOCKS).register(entries -> {
            entries.accept(Items.TOMATO_SEEDS);
            entries.accept(Items.RICE_SEEDS);
            entries.accept(Items.TEA_SEEDS);
        });
        ItemGroupEvents.modifyEntriesEvent(CreativeModeTabs.FUNCTIONAL_BLOCKS).register(entries -> {
            entries.accept(Items.VAT);
        });

        if (REGISTER_LOCAL_KNIFE) {
            registerItem("knife", KNIFE);
        }
        registerItem("glass", GLASS);
        registerItem("ender_cupcake", ENDER_CUPCAKE);
        registerItem("cola_extract", COLA_EXTRACT);
        registerItem("cola_powder", COLA_POWDER);
        registerItem("ultimate_burger", ULTIMATE_BURGER);
        registerItem("glass_of_water", GLASS_OF_WATER);
        registerItem("apple_pie", APPLE_PIE);
        registerItem("sweet_berry_pie", SWEET_BERRY_PIE);
        registerItem("teacup", TEACUP);
        registerItem("full_teacup_0", FULL_TEACUP_0);
        registerItem("full_teacup_1", FULL_TEACUP_1);
        registerItem("full_teacup_2", FULL_TEACUP_2);
        registerItem("full_teacup_3", FULL_TEACUP_3);
        registerItem("full_teacup_4", FULL_TEACUP_4);
        registerItem("full_teacup_5", FULL_TEACUP_5);
        registerItem("full_teacup_6", FULL_TEACUP_6);
        registerItem("full_teapot_0", FULL_TEAPOT_0);
        registerItem("full_teapot_1", FULL_TEAPOT_1);
        registerItem("full_teapot_2", FULL_TEAPOT_2);
        registerItem("full_teapot_3", FULL_TEAPOT_3);
        registerItem("full_teapot_4", FULL_TEAPOT_4);
        registerItem("full_teapot_5", FULL_TEAPOT_5);
        registerItem("full_teapot_6", FULL_TEAPOT_6);
        registerItem("full_teapot_7", FULL_TEAPOT_7);
        registerItem("hot_teapot_0", HOT_TEAPOT_0);
        registerItem("hot_teapot_1", HOT_TEAPOT_1);
        registerItem("hot_teapot_2", HOT_TEAPOT_2);
        registerItem("hot_teapot_3", HOT_TEAPOT_3);
        registerItem("hot_teapot_4", HOT_TEAPOT_4);
        registerItem("hot_teapot_5", HOT_TEAPOT_5);
        registerItem("hot_teapot_6", HOT_TEAPOT_6);
        registerItem("hot_teapot_7", HOT_TEAPOT_7);
        registerItem("teapot", TEAPOT);
        registerItem("tea_seeds", TEA_SEEDS);
        registerItem("tea_dried", TEA_DRIED);
        registerItem("tea_leaf", TEA_LEAF);
        registerItem("golden_cupcake", GOLDEN_CUPCAKE);
        registerItem("tomato", TOMATO);
        registerItem("tomato_seeds", TOMATO_SEEDS);
        registerItem("rice_seeds", RICE_SEEDS);
        registerItem("vat", VAT);
        registerItem("cheese_wheel", CHEESE_WHEEL);
        registerItem("apple_cupcake", APPLE_CUPCAKE);
        registerItem("pumpkin_cupcake", PUMPKIN_CUPCAKE);
        registerItem("cocoa_cupcake", COCOA_CUPCAKE);
        registerItem("melon_cupcake", MELON_CUPCAKE);
        registerItem("carrot_cupcake", CARROT_CUPCAKE);
        registerItem("fancy_apple_cupcake", FANCY_APPLE_CUPCAKE);
        registerItem("fancy_pumpkin_cupcake", FANCY_PUMPKIN_CUPCAKE);
        registerItem("glowberry_cupcake", GLOWBERRY_CUPCAKE);
        registerItem("donut", DONUT);
        registerItem("fancy_donut", FANCY_DONUT);
        registerItem("sprinkles", SPRINKLES);
        registerItem("chocolate", CHOCOLATE);
        registerItem("bun", BUN);
        registerItem("raw_patty", RAW_PATTY);
        registerItem("cooked_patty", COOKED_PATTY);
        registerItem("raw_chicken_patty", RAW_CHICKEN_PATTY);
        registerItem("cooked_chicken_patty", COOKED_CHICKEN_PATTY);
        registerItem("hamburger", HAMBURGER);
        registerItem("chicken_burger", CHICKEN_BURGER);
        registerItem("mushroom_burger", MUSHROOM_BURGER);
        registerItem("ultimate_bottom", ULTIMATE_BOTTOM);
        registerItem("ultimate_top", ULTIMATE_TOP);
        registerItem("cheeseburger", CHEESEBURGER);
        registerItem("rotten_burger", ROTTEN_BURGER);
        registerItem("raw_sausage", RAW_SAUSAGE);
        registerItem("cooked_sausage", COOKED_SAUSAGE);
        registerItem("hotdog", HOTDOG);
        registerItem("fish_bread", FISH_BREAD);
        registerItem("daisy_sandwich", DAISY_SANDWICH);
        registerItem("chicken_wrap", CHICKEN_WRAP);
        registerItem("raw_schnitzel", RAW_SCHNITZEL);
        registerItem("cooked_schnitzel", COOKED_SCHNITZEL);
        registerItem("fried_egg", FRIED_EGG);
        registerItem("croissant", CROISSANT);
        registerItem("potato_slices", POTATO_SLICES);
        registerItem("potato_fries", POTATO_FRIES);
        registerItem("shish_kebab", SHISH_KEBAB);
        registerItem("tomato_slices", TOMATO_SLICES);
        registerItem("ice_tea", ICE_TEA);
        registerItem("apple_juice", APPLE_JUICE);
        registerItem("carrot_juice", CARROT_JUICE);
        registerItem("melon_juice", MELON_JUICE);
        registerItem("pumpkin_juice", PUMPKIN_JUICE);
        registerItem("tomato_juice", TOMATO_JUICE);
        registerItem("wheat_juice", WHEAT_JUICE);
        registerItem("glass_of_milk", GLASS_OF_MILK);
        registerItem("sweet_berry_juice", SWEET_BERRY_JUICE);
        registerItem("ayran", AYRAN);
        registerItem("sake", SAKE);
        registerItem("carbonated_water", CARBONATED_WATER);
        registerItem("soda", SODA);
        registerItem("cola", COLA);
        registerItem("oyakodon", OYAKODON);
        registerItem("beef_donburi", BEEF_DONBURI);
        registerItem("egg_sushi", EGG_SUSHI);
        registerItem("nigiri_sushi", NIGIRI_SUSHI);
        registerItem("omurice", OMURICE);
        registerItem("riceball", RICEBALL);
        registerItem("sushi", SUSHI);
        registerItem("cooked_rice", COOKED_RICE);
        registerItem("sashimi", SASHIMI);
        registerItem("rice_pudding", RICE_PUDDING);
        registerItem("baked_rice_pudding", BAKED_RICE_PUDDING);
        registerItem("sweet_berry_cupcake_fancy", SWEET_BERRY_CUPCAKE_FANCY);
        registerItem("sweet_berry_cupcake", SWEET_BERRY_CUPCAKE);
        registerItem("doner_slice", DONER_SLICE);
        registerItem("yoghurt", YOGHURT);
        registerItem("honeyberry_yoghurt", HONEYBERRY_YOGHURT);
        registerItem("honey_cupcake", HONEY_CUPCAKE);
        registerItem("doner_wrap", DONER_WRAP);
        registerItem("chubby_doner", CHUBBY_DONER);
        registerItem("alexander", ALEXANDER);
        registerItem("raw_shish_kebab", RAW_SHISH_KEBAB);
        registerItem("cheese_slice", CHEESE_SLICE);
        registerItem("cheese_toast", CHEESE_TOAST);
        registerItem("squid_ink_paella", SQUID_INK_PAELLA);
        registerItem("glow_squid_ink_paella", GLOW_SQUID_INK_PAELLA);
        registerItem("raw_pizza_pepperoni_pepperoni_pepperoni", RAW_PIZZA_PEPPERONI_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_mushroom_pepperoni_pepperoni", RAW_PIZZA_MUSHROOM_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_mushroom_mushroom_pepperoni", RAW_PIZZA_MUSHROOM_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_mushroom_mushroom_mushroom", RAW_PIZZA_MUSHROOM_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_meat_pepperoni_pepperoni", RAW_PIZZA_MEAT_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_meat_mushroom_pepperoni", RAW_PIZZA_MEAT_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_meat_mushroom_mushroom", RAW_PIZZA_MEAT_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_meat_meat_pepperoni", RAW_PIZZA_MEAT_MEAT_PEPPERONI);
        registerItem("raw_pizza_meat_meat_mushroom", RAW_PIZZA_MEAT_MEAT_MUSHROOM);
        registerItem("raw_pizza_meat_meat_meat", RAW_PIZZA_MEAT_MEAT_MEAT);
        registerItem("raw_pizza_fish_pepperoni_pepperoni", RAW_PIZZA_FISH_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_fish_mushroom_pepperoni", RAW_PIZZA_FISH_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_fish_mushroom_mushroom", RAW_PIZZA_FISH_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_fish_meat_pepperoni", RAW_PIZZA_FISH_MEAT_PEPPERONI);
        registerItem("raw_pizza_fish_meat_mushroom", RAW_PIZZA_FISH_MEAT_MUSHROOM);
        registerItem("raw_pizza_fish_meat_meat", RAW_PIZZA_FISH_MEAT_MEAT);
        registerItem("raw_pizza_fish_fish_pepperoni", RAW_PIZZA_FISH_FISH_PEPPERONI);
        registerItem("raw_pizza_fish_fish_mushroom", RAW_PIZZA_FISH_FISH_MUSHROOM);
        registerItem("raw_pizza_fish_fish_meat", RAW_PIZZA_FISH_FISH_MEAT);
        registerItem("raw_pizza_fish_fish_fish", RAW_PIZZA_FISH_FISH_FISH);
        registerItem("raw_pizza_chicken_pepperoni_pepperoni", RAW_PIZZA_CHICKEN_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_chicken_mushroom_pepperoni", RAW_PIZZA_CHICKEN_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_chicken_mushroom_mushroom", RAW_PIZZA_CHICKEN_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_chicken_meat_pepperoni", RAW_PIZZA_CHICKEN_MEAT_PEPPERONI);
        registerItem("raw_pizza_chicken_meat_mushroom", RAW_PIZZA_CHICKEN_MEAT_MUSHROOM);
        registerItem("raw_pizza_chicken_meat_meat", RAW_PIZZA_CHICKEN_MEAT_MEAT);
        registerItem("raw_pizza_chicken_fish_pepperoni", RAW_PIZZA_CHICKEN_FISH_PEPPERONI);
        registerItem("raw_pizza_chicken_fish_mushroom", RAW_PIZZA_CHICKEN_FISH_MUSHROOM);
        registerItem("raw_pizza_chicken_fish_meat", RAW_PIZZA_CHICKEN_FISH_MEAT);
        registerItem("raw_pizza_chicken_fish_fish", RAW_PIZZA_CHICKEN_FISH_FISH);
        registerItem("raw_pizza_chicken_chicken_pepperoni", RAW_PIZZA_CHICKEN_CHICKEN_PEPPERONI);
        registerItem("raw_pizza_chicken_chicken_mushroom", RAW_PIZZA_CHICKEN_CHICKEN_MUSHROOM);
        registerItem("raw_pizza_chicken_chicken_meat", RAW_PIZZA_CHICKEN_CHICKEN_MEAT);
        registerItem("raw_pizza_chicken_chicken_fish", RAW_PIZZA_CHICKEN_CHICKEN_FISH);
        registerItem("raw_pizza_chicken_chicken_chicken", RAW_PIZZA_CHICKEN_CHICKEN_CHICKEN);
        registerItem("raw_pizza_pepperoni_pepperoni", RAW_PIZZA_PEPPERONI_PEPPERONI);
        registerItem("raw_pizza_mushroom_pepperoni", RAW_PIZZA_MUSHROOM_PEPPERONI);
        registerItem("raw_pizza_mushroom_mushroom", RAW_PIZZA_MUSHROOM_MUSHROOM);
        registerItem("raw_pizza_meat_pepperoni", RAW_PIZZA_MEAT_PEPPERONI);
        registerItem("raw_pizza_meat_mushroom", RAW_PIZZA_MEAT_MUSHROOM);
        registerItem("raw_pizza_meat_meat", RAW_PIZZA_MEAT_MEAT);
        registerItem("raw_pizza_fish_pepperoni", RAW_PIZZA_FISH_PEPPERONI);
        registerItem("raw_pizza_fish_mushroom", RAW_PIZZA_FISH_MUSHROOM);
        registerItem("raw_pizza_fish_meat", RAW_PIZZA_FISH_MEAT);
        registerItem("raw_pizza_fish_fish", RAW_PIZZA_FISH_FISH);
        registerItem("raw_pizza_chicken_pepperoni", RAW_PIZZA_CHICKEN_PEPPERONI);
        registerItem("raw_pizza_chicken_mushroom", RAW_PIZZA_CHICKEN_MUSHROOM);
        registerItem("raw_pizza_chicken_meat", RAW_PIZZA_CHICKEN_MEAT);
        registerItem("raw_pizza_chicken_fish", RAW_PIZZA_CHICKEN_FISH);
        registerItem("raw_pizza_chicken_chicken", RAW_PIZZA_CHICKEN_CHICKEN);
        registerItem("raw_pizza_pepperoni", RAW_PIZZA_PEPPERONI);
        registerItem("raw_pizza_mushroom", RAW_PIZZA_MUSHROOM);
        registerItem("raw_pizza_meat", RAW_PIZZA_MEAT);
        registerItem("raw_pizza_fish", RAW_PIZZA_FISH);
        registerItem("raw_pizza_chicken", RAW_PIZZA_CHICKEN);
        registerItem("raw_pizza", RAW_PIZZA);
        registerItem("pizza_pepperoni_pepperoni_pepperoni", PIZZA_PEPPERONI_PEPPERONI_PEPPERONI);
        registerItem("pizza_mushroom_pepperoni_pepperoni", PIZZA_MUSHROOM_PEPPERONI_PEPPERONI);
        registerItem("pizza_mushroom_mushroom_pepperoni", PIZZA_MUSHROOM_MUSHROOM_PEPPERONI);
        registerItem("pizza_mushroom_mushroom_mushroom", PIZZA_MUSHROOM_MUSHROOM_MUSHROOM);
        registerItem("pizza_meat_pepperoni_pepperoni", PIZZA_MEAT_PEPPERONI_PEPPERONI);
        registerItem("pizza_meat_mushroom_pepperoni", PIZZA_MEAT_MUSHROOM_PEPPERONI);
        registerItem("pizza_meat_mushroom_mushroom", PIZZA_MEAT_MUSHROOM_MUSHROOM);
        registerItem("pizza_meat_meat_pepperoni", PIZZA_MEAT_MEAT_PEPPERONI);
        registerItem("pizza_meat_meat_mushroom", PIZZA_MEAT_MEAT_MUSHROOM);
        registerItem("pizza_meat_meat_meat", PIZZA_MEAT_MEAT_MEAT);
        registerItem("pizza_fish_pepperoni_pepperoni", PIZZA_FISH_PEPPERONI_PEPPERONI);
        registerItem("pizza_fish_mushroom_pepperoni", PIZZA_FISH_MUSHROOM_PEPPERONI);
        registerItem("pizza_fish_mushroom_mushroom", PIZZA_FISH_MUSHROOM_MUSHROOM);
        registerItem("pizza_fish_meat_pepperoni", PIZZA_FISH_MEAT_PEPPERONI);
        registerItem("pizza_fish_meat_mushroom", PIZZA_FISH_MEAT_MUSHROOM);
        registerItem("pizza_fish_meat_meat", PIZZA_FISH_MEAT_MEAT);
        registerItem("pizza_fish_fish_pepperoni", PIZZA_FISH_FISH_PEPPERONI);
        registerItem("pizza_fish_fish_mushroom", PIZZA_FISH_FISH_MUSHROOM);
        registerItem("pizza_fish_fish_meat", PIZZA_FISH_FISH_MEAT);
        registerItem("pizza_fish_fish_fish", PIZZA_FISH_FISH_FISH);
        registerItem("pizza_chicken_pepperoni_pepperoni", PIZZA_CHICKEN_PEPPERONI_PEPPERONI);
        registerItem("pizza_chicken_mushroom_pepperoni", PIZZA_CHICKEN_MUSHROOM_PEPPERONI);
        registerItem("pizza_chicken_mushroom_mushroom", PIZZA_CHICKEN_MUSHROOM_MUSHROOM);
        registerItem("pizza_chicken_meat_pepperoni", PIZZA_CHICKEN_MEAT_PEPPERONI);
        registerItem("pizza_chicken_meat_mushroom", PIZZA_CHICKEN_MEAT_MUSHROOM);
        registerItem("pizza_chicken_meat_meat", PIZZA_CHICKEN_MEAT_MEAT);
        registerItem("pizza_chicken_fish_pepperoni", PIZZA_CHICKEN_FISH_PEPPERONI);
        registerItem("pizza_chicken_fish_mushroom", PIZZA_CHICKEN_FISH_MUSHROOM);
        registerItem("pizza_chicken_fish_meat", PIZZA_CHICKEN_FISH_MEAT);
        registerItem("pizza_chicken_fish_fish", PIZZA_CHICKEN_FISH_FISH);
        registerItem("pizza_chicken_chicken_pepperoni", PIZZA_CHICKEN_CHICKEN_PEPPERONI);
        registerItem("pizza_chicken_chicken_mushroom", PIZZA_CHICKEN_CHICKEN_MUSHROOM);
        registerItem("pizza_chicken_chicken_meat", PIZZA_CHICKEN_CHICKEN_MEAT);
        registerItem("pizza_chicken_chicken_fish", PIZZA_CHICKEN_CHICKEN_FISH);
        registerItem("pizza_chicken_chicken_chicken", PIZZA_CHICKEN_CHICKEN_CHICKEN);
        registerItem("pizza_pepperoni_pepperoni", PIZZA_PEPPERONI_PEPPERONI);
        registerItem("pizza_mushroom_pepperoni", PIZZA_MUSHROOM_PEPPERONI);
        registerItem("pizza_mushroom_mushroom", PIZZA_MUSHROOM_MUSHROOM);
        registerItem("pizza_meat_pepperoni", PIZZA_MEAT_PEPPERONI);
        registerItem("pizza_meat_mushroom", PIZZA_MEAT_MUSHROOM);
        registerItem("pizza_meat_meat", PIZZA_MEAT_MEAT);
        registerItem("pizza_fish_pepperoni", PIZZA_FISH_PEPPERONI);
        registerItem("pizza_fish_mushroom", PIZZA_FISH_MUSHROOM);
        registerItem("pizza_fish_meat", PIZZA_FISH_MEAT);
        registerItem("pizza_fish_fish", PIZZA_FISH_FISH);
        registerItem("pizza_chicken_pepperoni", PIZZA_CHICKEN_PEPPERONI);
        registerItem("pizza_chicken_mushroom", PIZZA_CHICKEN_MUSHROOM);
        registerItem("pizza_chicken_meat", PIZZA_CHICKEN_MEAT);
        registerItem("pizza_chicken_fish", PIZZA_CHICKEN_FISH);
        registerItem("pizza_chicken_chicken", PIZZA_CHICKEN_CHICKEN);
        registerItem("pizza_pepperoni", PIZZA_PEPPERONI);
        registerItem("pizza_mushroom", PIZZA_MUSHROOM);
        registerItem("pizza_meat", PIZZA_MEAT);
        registerItem("pizza_fish", PIZZA_FISH);
        registerItem("pizza_chicken", PIZZA_CHICKEN);
        registerItem("pizza", PIZZA);
    }
}
