modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "xerca"
logoFile = "assets/xercamusic/textures/item/music_sheet.png"
description = '''
Compose and play music in Minecraft
'''

[[mixins]]
config = "xercamusic.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
