# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.242
# Mod Properties
mod_id=xercatools
mod_name=Xerca Tools & Weapons
mod_version=1.21.1-1.2.2
mod_license=GPL-3.0
mod_group_id=xerca
