from copy import deepcopy

from recipe_generator import *

shaped_recipes = [
    ShapedRecipe([' l ', 'lel', ' l '], {'id': 'xercafood:flask'}, {'e': {'item': 'minecraft:ender_eye'}, 'l': {'item': 'minecraft:leather'}}, {'item': 'minecraft:ender_eye'}, ""),
    ShapedRecipe(['sas', 'mem', 'www'], {'id': 'xercafood:glowberry_cupcake', 'count': 6}, {'a': {'item': 'minecraft:glow_berries'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:glow_berries'}, ""),
    ShapedRecipe(['www', 'mem', 'sas'], {'id': 'xercafood:ender_cupcake', 'count': 6}, {'a': {'item': 'minecraft:chorus_fruit'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:chorus_fruit'}, ""),
    ShapedRecipe(['sas', 'mem', 'www'], {'id': 'xercafood:item_honey_cupcake', 'count': 6}, {'a': {'item': 'minecraft:honey_bottle'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:honey_bottle'}, "cupcake"),
    ShapedRecipe(['sas', 'mem', 'www'], {'id': 'xercafood:sweet_berry_cupcake', 'count': 6}, {'a': {'item': 'minecraft:sweet_berries'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:sweet_berries'}, "cupcake"),
    ShapedRecipe(['sas', 'mem', 'www'], {'id': 'xercafood:item_apple_cupcake', 'count': 6}, {'a': {'item': 'minecraft:apple'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:apple'}, "cupcake"),
    ShapedRecipe(['ADA', 'BEB', 'CCC'], {'id': 'xercafood:sweet_berry_pie'}, {'A': {'item': 'minecraft:sweet_berries'}, 'B': {'item': 'minecraft:sugar'}, 'C': {'item': 'minecraft:wheat'}, 'D': {'item': 'minecraft:milk_bucket'}, 'E': {'item': 'minecraft:egg'}}, {'item': 'minecraft:sweet_berries'}, ""),
    ShapedRecipe(['ADA', 'BEB', 'CCC'], {'id': 'xercafood:item_apple_pie'}, {'A': {'item': 'minecraft:apple'}, 'B': {'item': 'minecraft:sugar'}, 'C': {'item': 'minecraft:wheat'}, 'D': {'item': 'minecraft:milk_bucket'}, 'E': {'item': 'minecraft:egg'}}, {'item': 'minecraft:apple'}, ""),
    ShapedRecipe(['lll', 'lll', 'lll'], {'id': 'xercafood:item_block_leather'}, {'l': {'item': 'minecraft:leather'}}, {'item': 'minecraft:leather'}, ""),
    ShapedRecipe(['lll', 'lll', 'lll'], {'id': 'xercafood:item_block_straw'}, {'l': {'item': 'minecraft:sugar_cane'}}, {'item': 'minecraft:sugar_cane'}, ""),
    ShapedRecipe(['www', '   ', 'www'], {'id': 'xercafood:item_bookcase'}, {'w': {'tag': 'minecraft:planks'}}, {'tag': 'minecraft:planks'}, ""),
    ShapedRecipe(['sas', 'mem', 'www'], {'id': 'xercafood:item_carrot_cupcake', 'count': 6}, {'a': {'item': 'minecraft:carrot'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:carrot'}, "cupcake"),
    ShapedRecipe([' b ', 'dc ', ' b '], {'id': 'xercafood:item_chicken_burger'}, {'b': {'item': 'xercafood:item_bun'}, 'c': {'item': 'xercafood:item_cooked_chicken_patty'}, 'd': {'item': 'xercafood:item_tomato_slices'}}, {'item': 'xercafood:item_bun'}, ""),
    ShapedRecipe([' wc', 'wcw', 'cw '], {'id': 'xercafood:item_chicken_wrap', 'count': 4}, {'c': {'item': 'minecraft:cooked_chicken'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'minecraft:cooked_chicken'}, "chicken_wrap"),
    ShapedRecipe(['cw ', 'wcw', ' wc'], {'id': 'xercafood:item_chicken_wrap', 'count': 4}, {'c': {'item': 'minecraft:cooked_chicken'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'minecraft:cooked_chicken'}, "chicken_wrap"),
    ShapedRecipe([' s ', 'cmc', ' s '], {'id': 'xercafood:item_chocolate', 'count': 6}, {'s': {'item': 'minecraft:sugar'}, 'c': {'item': 'minecraft:cocoa_beans'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:cocoa_beans'}, ""),
    ShapedRecipe(['sps', 'mem', 'www'], {'id': 'xercafood:item_cocoa_cupcake', 'count': 6}, {'p': {'item': 'minecraft:cocoa_beans'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:cocoa_beans'}, "cupcake"),
    ShapedRecipe([' c ', 'cgc', ' c '], {'id': 'xercafood:item_confetti_ball', 'count': 2}, {'c': {'item': 'xercafood:item_confetti'}, 'g': {'item': 'minecraft:gunpowder'}}, {'item': 'xercafood:item_confetti'}, ""),
    ShapedRecipe(['sws', 'www'], {'id': 'xercafood:item_croissant', 'count': 2}, {'s': {'item': 'minecraft:sugar'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'minecraft:wheat'}, ""),
    ShapedRecipe([' b ', 'yyy', ' b '], {'id': 'xercafood:item_daisy_sandwich', 'count': 3}, {'b': {'item': 'minecraft:bread'}, 'y': {'item': 'minecraft:oxeye_daisy'}}, {'item': 'minecraft:oxeye_daisy'}, ""),
    ShapedRecipe(['tst', ' s ', ' s '], {'id': 'xercafood:item_diamond_warhammer'}, {'s': {'item': 'minecraft:stick'}, 't': {'item': 'minecraft:diamond'}}, {'item': 'minecraft:diamond'}, ""),
    ShapedRecipe(['sws', 'wxw', 'sws'], {'id': 'xercafood:item_donut', 'count': 4}, {'s': {'item': 'minecraft:sugar'}, 'w': {'item': 'minecraft:wheat'}, 'x': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:wheat'}, ""),
    ShapedRecipe(['s', 'c'], {'id': 'xercafood:sweet_berry_cupcake_fancy'}, {'s': {'item': 'xercafood:item_sprinkles'}, 'c': {'item': 'xercafood:sweet_berry_cupcake'}}, {'item': 'xercafood:item_sprinkles'}, "fancy_cupcake"),
    ShapedRecipe(['s', 'c'], {'id': 'xercafood:item_fancy_apple_cupcake'}, {'s': {'item': 'xercafood:item_sprinkles'}, 'c': {'item': 'xercafood:item_apple_cupcake'}}, {'item': 'xercafood:item_sprinkles'}, "fancy_cupcake"),
    ShapedRecipe(['s', 'd'], {'id': 'xercafood:item_fancy_donut'}, {'s': {'item': 'xercafood:item_sprinkles'}, 'd': {'item': 'xercafood:item_donut'}}, {'item': 'xercafood:item_sprinkles'}, ""),
    ShapedRecipe(['s', 'c'], {'id': 'xercafood:item_fancy_pumpkin_cupcake'}, {'s': {'item': 'xercafood:item_sprinkles'}, 'c': {'item': 'xercafood:item_pumpkin_cupcake'}}, {'item': 'xercafood:item_sprinkles'}, "fancy_cupcake"),
    ShapedRecipe(['b', 'h', 'b'], {'id': 'xercafood:item_fish_bread', 'count': 2}, {'b': {'item': 'minecraft:bread'}, 'h': {'item': 'minecraft:cooked_cod'}}, {'item': 'minecraft:cooked_cod'}, ""),
    ShapedRecipe(['c c', ' c '], {'id': 'xercafood:item_glass', 'count': 3}, {'c': {'item': 'minecraft:glass_pane'}}, {'item': 'minecraft:glass_pane'}, ""),
    ShapedRecipe(['nan', 'mem', 'www'], {'id': 'xercafood:item_golden_cupcake'}, {'a': {'item': 'minecraft:golden_apple', 'data': 0}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}, 'n': {'item': 'minecraft:gold_nugget'}}, None, ""),
    ShapedRecipe(['tst', ' s ', ' s '], {'id': 'xercafood:item_gold_warhammer'}, {'s': {'item': 'minecraft:stick'}, 't': {'item': 'minecraft:gold_ingot'}}, {'item': 'minecraft:gold_ingot'}, ""),
    ShapedRecipe([' b ', 'dh ', ' b '], {'id': 'xercafood:item_hamburger'}, {'b': {'item': 'xercafood:item_bun'}, 'd': {'item': 'xercafood:item_tomato_slices'}, 'h': {'item': 'xercafood:item_cooked_patty'}}, {'item': 'xercafood:item_bun'}, ""),
    ShapedRecipe([' b ', 'dhc', ' b '], {'id': 'xercafood:cheeseburger'}, {'b': {'item': 'xercafood:item_bun'}, 'd': {'item': 'xercafood:item_tomato_slices'}, 'h': {'item': 'xercafood:item_cooked_patty'}, 'c': {'item': 'xercafood:cheese_slice'}}, {'item': 'xercafood:item_bun'}, ""),
    ShapedRecipe(['b', 'p', 'b'], {'id': 'xercafood:item_hotdog'}, {'p': {'item': 'xercafood:item_cooked_sausage'}, 'b': {'item': 'xercafood:item_bun'}}, {'item': 'xercafood:item_bun'}, ""),
    ShapedRecipe(['tst', ' s ', ' s '], {'id': 'xercafood:item_iron_warhammer'}, {'s': {'item': 'minecraft:stick'}, 't': {'item': 'minecraft:iron_ingot'}}, {'item': 'minecraft:iron_ingot'}, ""),
    ShapedRecipe(['i', 's'], {'id': 'xercafood:item_knife'}, {'s': {'item': 'minecraft:stick'}, 'i': {'item': 'minecraft:iron_ingot'}}, {'item': 'minecraft:iron_ingot'}, ""),
    ShapedRecipe(['sps', 'mem', 'www'], {'id': 'xercafood:item_melon_cupcake', 'count': 6}, {'p': {'item': 'minecraft:melon'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:melon'}, "cupcake"),
    ShapedRecipe([' b ', 'dmn', ' b '], {'id': 'xercafood:item_mushroom_burger'}, {'b': {'item': 'xercafood:item_bun'}, 'd': {'item': 'xercafood:item_tomato_slices'}, 'm': {'item': 'minecraft:brown_mushroom'}, 'n': {'item': 'minecraft:red_mushroom'}}, {'item': 'xercafood:item_bun'}, ""),
    ShapedRecipe(['sps', 'mem', 'www'], {'id': 'xercafood:item_pumpkin_cupcake', 'count': 6}, {'p': {'item': 'minecraft:pumpkin'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:pumpkin'}, "cupcake"),
    ShapedRecipe([' w ', 'wcw', ' w '], {'id': 'xercafood:item_raw_schnitzel', 'count': 2}, {'c': {'item': 'minecraft:chicken'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'minecraft:chicken'}, ""),
    ShapedRecipe(['b', 'r', 'b'], {'id': 'xercafood:item_rotten_burger'}, {'b': {'item': 'xercafood:item_bun'}, 'r': {'item': 'minecraft:rotten_flesh'}}, {'item': 'xercafood:item_bun'}, ""),
    ShapedRecipe(['tst', ' s ', ' s '], {'id': 'xercafood:item_stone_warhammer'}, {'s': {'item': 'minecraft:stick'}, 't': {'item': 'minecraft:cobblestone'}}, {'item': 'minecraft:cobblestone'}, ""),
    ShapedRecipe(['c c', ' c '], {'id': 'xercafood:item_teacup', 'count': 2}, {'c': {'item': 'minecraft:clay_ball'}}, {'item': 'minecraft:clay_ball'}, ""),
    ShapedRecipe([' c ', 'c c', 'ccc'], {'id': 'xercafood:item_teapot'}, {'c': {'item': 'minecraft:clay_ball'}}, {'item': 'minecraft:clay_ball'}, ""),
    ShapedRecipe(['mnm', ' p ', ' b '], {'id': 'xercafood:item_ultimate_bottom'}, {'p': {'item': 'xercafood:item_cooked_patty'}, 'b': {'item': 'xercafood:item_bun'}, 'm': {'item': 'minecraft:brown_mushroom'}, 'n': {'item': 'minecraft:red_mushroom'}}, {'item': 'xercafood:item_bun'}, "ultimate_bottom"),
    ShapedRecipe(['nmn', ' p ', ' b '], {'id': 'xercafood:item_ultimate_bottom'}, {'p': {'item': 'xercafood:item_cooked_patty'}, 'b': {'item': 'xercafood:item_bun'}, 'm': {'item': 'minecraft:brown_mushroom'}, 'n': {'item': 'minecraft:red_mushroom'}}, {'item': 'xercafood:item_bun'}, "ultimate_bottom"),
    ShapedRecipe([' t ', ' e ', ' b '], {'id': 'xercafood:item_ultimate_burger'}, {'b': {'item': 'xercafood:item_ultimate_bottom'}, 't': {'item': 'xercafood:item_ultimate_top'}, 'e': {'item': 'xercafood:item_bun'}}, {'item': 'xercafood:item_bun'}, ""),
    ShapedRecipe([' b ', 'tst', ' c '], {'id': 'xercafood:item_ultimate_top'}, {'b': {'item': 'xercafood:item_bun'}, 'c': {'item': 'xercafood:item_cooked_chicken_patty'}, 't': {'item': 'xercafood:item_tomato_slices'}, 's': {'item': 'xercafood:cheese_slice'}}, {'item': 'xercafood:item_bun'}, ""),
    ShapedRecipe([' wd', 'wdw', 'dw '], {'id': 'xercafood:item_doner_wrap', 'count': 4}, {'d': {'item': 'xercafood:doner_slice'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'xercafood:doner_slice'}, ""),
    ShapedRecipe([' b ', 'tdp', ' b '], {'id': 'xercafood:item_chubby_doner'}, {'b': {'item': 'xercafood:item_bun'}, 't': {'item': 'xercafood:item_tomato_slices'}, 'd': {'item': 'xercafood:doner_slice'}, 'p': {'item': 'xercafood:item_potato_fries'}}, {'item': 'xercafood:doner_slice'}, ""),
    ShapedRecipe(['iis', ' s ', 's  '], {'id': 'xercafood:wooden_scythe'}, {'i': {'tag': 'minecraft:planks'}, 's': {'item': 'minecraft:stick'}}, {'tag': 'minecraft:planks'}),
    ShapedRecipe(['iis', ' s ', 's  '], {'id': 'xercafood:stone_scythe'}, {'i': {'item': 'minecraft:cobblestone'}, 's': {'item': 'minecraft:stick'}}, {'item': 'minecraft:cobblestone'}),
    ShapedRecipe(['iis', ' s ', 's  '], {'id': 'xercafood:iron_scythe'}, {'i': {'item': 'minecraft:iron_ingot'}, 's': {'item': 'minecraft:stick'}}, {'item': 'minecraft:iron_ingot'}),
    ShapedRecipe(['iis', ' s ', 's  '], {'id': 'xercafood:golden_scythe'}, {'i': {'item': 'minecraft:gold_ingot'}, 's': {'item': 'minecraft:stick'}}, {'item': 'minecraft:gold_ingot'}),
    ShapedRecipe(['iis', ' s ', 's  '], {'id': 'xercafood:diamond_scythe'}, {'i': {'item': 'minecraft:diamond'}, 's': {'item': 'minecraft:stick'}}, {'item': 'minecraft:diamond'}),

    # Court
    ShapedRecipe(['#s#', ' s ', ' s '], {'id': 'xercacourt:item_gavel'}, {'#': {'tag': 'minecraft:planks'}, 's': {'item': 'minecraft:stick'}}, {'tag': 'minecraft:planks'}, ""),
    ShapelessRecipe([{'item': 'minecraft:gold_nugget'}, {'item': 'minecraft:cookie'}], {'item': 'xercacourt:item_attorney_badge'}, {'item': 'minecraft:gold_nugget'}, ""),
    ShapelessRecipe([{'item': 'minecraft:gold_nugget'}, {'item': 'minecraft:poppy', 'data': 0}], {'item': 'xercacourt:item_prosecutor_badge'}, {'item': 'minecraft:gold_nugget'}, "pro_badge"),
    ShapelessRecipe([{'item': 'minecraft:gold_nugget'}, {'item': 'minecraft:dandelion', 'data': 0}], {'item': 'xercacourt:item_prosecutor_badge'}, {'item': 'minecraft:gold_nugget'}, "pro_badge"),

    # Cushion
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:black_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:black_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:blue_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:blue_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:brown_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:brown_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:cyan_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:cyan_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:gray_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:gray_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:green_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:green_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:light_blue_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:light_blue_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:light_gray_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:light_gray_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:lime_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:lime_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:magenta_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:magenta_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:orange_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:orange_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:pink_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:pink_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:purple_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:purple_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:red_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:red_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:white_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:white_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),
    ShapedRecipe(['#', 'f', '#'], {'id': 'xercacushion:yellow_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:yellow_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion"),

    # Terracotta tiles
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:black_terratile', 'count': 4}, {'t': {'item': 'minecraft:black_terracotta'}}, {'item': 'minecraft:black_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:blue_terratile', 'count': 4}, {'t': {'item': 'minecraft:blue_terracotta'}}, {'item': 'minecraft:blue_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:brown_terratile', 'count': 4}, {'t': {'item': 'minecraft:brown_terracotta'}}, {'item': 'minecraft:brown_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:cyan_terratile', 'count': 4}, {'t': {'item': 'minecraft:cyan_terracotta'}}, {'item': 'minecraft:cyan_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:gray_terratile', 'count': 4}, {'t': {'item': 'minecraft:gray_terracotta'}}, {'item': 'minecraft:gray_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:green_terratile', 'count': 4}, {'t': {'item': 'minecraft:green_terracotta'}}, {'item': 'minecraft:green_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:light_blue_terratile', 'count': 4}, {'t': {'item': 'minecraft:light_blue_terracotta'}}, {'item': 'minecraft:light_blue_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:light_gray_terratile', 'count': 4}, {'t': {'item': 'minecraft:light_gray_terracotta'}}, {'item': 'minecraft:light_gray_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:lime_terratile', 'count': 4}, {'t': {'item': 'minecraft:lime_terracotta'}}, {'item': 'minecraft:lime_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:magenta_terratile', 'count': 4}, {'t': {'item': 'minecraft:magenta_terracotta'}}, {'item': 'minecraft:magenta_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:orange_terratile', 'count': 4}, {'t': {'item': 'minecraft:orange_terracotta'}}, {'item': 'minecraft:orange_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:pink_terratile', 'count': 4}, {'t': {'item': 'minecraft:pink_terracotta'}}, {'item': 'minecraft:pink_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:purple_terratile', 'count': 4}, {'t': {'item': 'minecraft:purple_terracotta'}}, {'item': 'minecraft:purple_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:red_terratile', 'count': 4}, {'t': {'item': 'minecraft:red_terracotta'}}, {'item': 'minecraft:red_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:white_terratile', 'count': 4}, {'t': {'item': 'minecraft:white_terracotta'}}, {'item': 'minecraft:white_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:yellow_terratile', 'count': 4}, {'t': {'item': 'minecraft:yellow_terracotta'}}, {'item': 'minecraft:yellow_terracotta'}, "terratile"),
    ShapedRecipe(['tt', 'tt'], {'id': 'xercablocks:terratile', 'count': 4}, {'t': {'item': 'minecraft:terracotta'}}, {'item': 'minecraft:terracotta'}, "terratile"),

    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:black_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:black_terratile'}}, {'item': 'xercablocks:black_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:blue_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:blue_terratile'}}, {'item': 'xercablocks:blue_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:brown_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:brown_terratile'}}, {'item': 'xercablocks:brown_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:cyan_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:cyan_terratile'}}, {'item': 'xercablocks:cyan_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:gray_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:gray_terratile'}}, {'item': 'xercablocks:gray_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:green_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:green_terratile'}}, {'item': 'xercablocks:green_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:light_blue_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:light_blue_terratile'}}, {'item': 'xercablocks:light_blue_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:light_gray_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:light_gray_terratile'}}, {'item': 'xercablocks:light_gray_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:lime_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:lime_terratile'}}, {'item': 'xercablocks:lime_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:magenta_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:magenta_terratile'}}, {'item': 'xercablocks:magenta_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:orange_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:orange_terratile'}}, {'item': 'xercablocks:orange_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:pink_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:pink_terratile'}}, {'item': 'xercablocks:pink_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:purple_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:purple_terratile'}}, {'item': 'xercablocks:purple_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:red_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:red_terratile'}}, {'item': 'xercablocks:red_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:white_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:white_terratile'}}, {'item': 'xercablocks:white_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:yellow_terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:yellow_terratile'}}, {'item': 'xercablocks:yellow_terratile'}, ""),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'id': 'xercablocks:terratile_stairs', 'count': 4}, {'t': {'item': 'xercablocks:terratile'}}, {'item': 'xercablocks:terratile'}, ""),

    ShapedRecipe(['ttt'], {'id': 'xercablocks:black_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:black_terratile'}}, {'item': 'xercablocks:black_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:blue_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:blue_terratile'}}, {'item': 'xercablocks:blue_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:brown_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:brown_terratile'}}, {'item': 'xercablocks:brown_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:cyan_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:cyan_terratile'}}, {'item': 'xercablocks:cyan_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:gray_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:gray_terratile'}}, {'item': 'xercablocks:gray_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:green_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:green_terratile'}}, {'item': 'xercablocks:green_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:light_blue_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:light_blue_terratile'}}, {'item': 'xercablocks:light_blue_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:light_gray_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:light_gray_terratile'}}, {'item': 'xercablocks:light_gray_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:lime_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:lime_terratile'}}, {'item': 'xercablocks:lime_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:magenta_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:magenta_terratile'}}, {'item': 'xercablocks:magenta_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:orange_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:orange_terratile'}}, {'item': 'xercablocks:orange_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:pink_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:pink_terratile'}}, {'item': 'xercablocks:pink_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:purple_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:purple_terratile'}}, {'item': 'xercablocks:purple_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:red_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:red_terratile'}}, {'item': 'xercablocks:red_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:white_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:white_terratile'}}, {'item': 'xercablocks:white_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:yellow_terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:yellow_terratile'}}, {'item': 'xercablocks:yellow_terratile'}, ""),
    ShapedRecipe(['ttt'], {'id': 'xercablocks:terratile_slab', 'count': 6}, {'t': {'item': 'xercablocks:terratile'}}, {'item': 'xercablocks:terratile'}, ""),

    ShapedRecipe(['f', 'c'], {'id': 'xercatools:ender_bow'},  {'c': {'item': 'minecraft:crossbow'}, 'f': {'item': 'xercatools:flask'}}, {'item': 'xercatools:flask'}, ""),

    ShapedRecipe(['kk', 'pp', 'pp'], {'id': 'xercablocks:carving_station'},  {'p': {'tag': 'minecraft:planks'}, 'k': {'item': 'xercafood:item_knife'}}, {'item': 'xercafood:item_knife'}, ""),

    ShapedRecipe(['c c', 'ccc', 'i i'], {'id': 'xercafood:vat'},  {'c': {'item': 'minecraft:copper_ingot'}, 'i': {'item': 'minecraft:iron_ingot'}}, {'item': 'minecraft:copper_ingot'}, ""),
    ShapedRecipe(['ct ', 'www'], {'id': 'xercafood:raw_pizza'},  {'w': {'item': 'minecraft:wheat'}, 'c': {'item': 'xercafood:cheese_slice'}, 't': {'item': 'xercafood:item_tomato_slices'}}, {'item': 'xercafood:cheese_slice'}, "pizza_base"),
    ShapedRecipe(['tc ', 'www'], {'id': 'xercafood:raw_pizza'},  {'w': {'item': 'minecraft:wheat'}, 'c': {'item': 'xercafood:cheese_slice'}, 't': {'item': 'xercafood:item_tomato_slices'}}, {'item': 'xercafood:cheese_slice'}, "pizza_base"),
    ShapedRecipe(['b', 'c', 'b'], {'id': 'xercafood:cheese_toast'},  {'b': {'item': 'xercafood:item_bun'}, 'c': {'item': 'xercafood:cheese_slice'}}, {'item': 'xercafood:cheese_slice'}, ""),
    ShapedRecipe(['ses', 'www', 'www'], {'id': 'xercafood:cola', 'count': 6},  {'w': {'item': 'xercafood:carbonated_water'}, 'e': {'item': 'xercafood:cola_extract'}, 's': {'item': 'minecraft:snowball'}}, {'item': 'xercafood:carbonated_water'}, ""),

    ShapedRecipe(['aea', 'ece', 'aea'], {'id': 'xercaomni:omni_chest'},  {'e': {'item': 'minecraft:ender_eye'}, 'c': {'item': 'minecraft:ender_chest'}, 'a': {'item': 'minecraft:amethyst_block'}}, {'item': 'minecraft:ender_chest'}, ""),]

shapeless_recipes = [
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'xercafood:item_yoghurt'}], {'item': 'xercafood:item_ayran'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'minecraft:sweet_berries'}], {'item': 'xercafood:sweet_berry_juice'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'minecraft:apple'}], {'item': 'xercafood:item_apple_juice'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'minecraft:bread'}, {'item': 'xercafood:item_knife', 'data': 32767}], {'item': 'xercafood:item_bun', 'count': 2}, {'item': 'minecraft:bread'}),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'minecraft:carrot'}], {'item': 'xercafood:item_carrot_juice'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'minecraft:paper'}, {'item': 'minecraft:cyan_dye'}, {'item': 'minecraft:magenta_dye'}, {'item': 'minecraft:yellow_dye'}], {'item': 'xercafood:item_confetti', 'count': 12}, {'item': 'minecraft:paper'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'minecraft:milk_bucket'}], {'item': 'xercafood:item_glass_of_milk'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'minecraft:water_bucket'}], {'item': 'xercafood:item_glass_of_water'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'xercafood:item_knife'}, {'item': 'minecraft:fishing_rod'}], {'item': 'xercafood:item_grab_hook'}, {'item': 'minecraft:fishing_rod'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_tea_dried'}, {'item': 'xercafood:item_glass_of_water'}, {'item': 'minecraft:snowball'}, {'item': 'minecraft:sugar'}], {'item': 'xercafood:item_ice_tea'}, {'item': 'xercafood:item_glass_of_water'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'minecraft:melon'}], {'item': 'xercafood:item_melon_juice'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'minecraft:potato'}, {'item': 'xercafood:item_knife', 'data': 32767}], {'item': 'xercafood:item_potato_slices', 'count': 2}, {'item': 'minecraft:potato'}),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'minecraft:pumpkin'}], {'item': 'xercafood:item_pumpkin_juice'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'minecraft:chicken'}, {'item': 'xercafood:item_knife', 'data': 32767}], {'item': 'xercafood:item_raw_chicken_patty', 'count': 2}, {'item': 'minecraft:chicken'}),
    ShapelessRecipe([{'item': 'minecraft:beef'}, {'item': 'xercafood:item_knife', 'data': 32767}], {'item': 'xercafood:item_raw_patty', 'count': 2}, {'item': 'minecraft:beef'}),
    ShapelessRecipe([{'item': 'minecraft:porkchop'}, {'item': 'xercafood:item_knife', 'data': 32767}], {'item': 'xercafood:item_raw_sausage', 'count': 2}, {'item': 'minecraft:porkchop'}),
    ShapelessRecipe([{'item': 'minecraft:sugar'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:cyan_dye'}, {'item': 'minecraft:magenta_dye'}, {'item': 'minecraft:yellow_dye'}], {'item': 'xercafood:item_sprinkles', 'count': 12}, {'item': 'minecraft:sugar'}),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'xercafood:item_tomato'}], {'item': 'xercafood:item_tomato_juice'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'xercafood:item_tomato'}], {'item': 'xercafood:item_tomato_seeds'}, {'item': 'xercafood:item_tomato'}),
    ShapelessRecipe([{'item': 'xercafood:item_tomato'}, {'item': 'xercafood:item_knife', 'data': 32767}], {'item': 'xercafood:item_tomato_slices', 'count': 3}, {'item': 'xercafood:item_tomato'}),
    ShapelessRecipe([{'item': 'xercafood:cheese_wheel'}, {'item': 'xercafood:item_knife', 'data': 32767}], {'item': 'xercafood:cheese_slice', 'count': 4}, {'item': 'xercafood:cheese_wheel'}),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'minecraft:wheat'}, {'item': 'minecraft:wheat'}], {'item': 'xercafood:item_wheat_juice'}, {'item': 'xercafood:item_glass'}),
    ShapelessRecipe([{'item': 'xercafood:item_block_straw'}], {'item': 'minecraft:sugar_cane', 'count': 9}, {'item': 'xercafood:item_block_straw'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_block_leather'}], {'item': 'minecraft:leather', 'count': 9}, {'item': 'xercafood:item_block_leather'}, ""),
    ShapelessRecipe([{'item': 'xercafood:carbonated_water'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:snowball'}], {'item': 'xercafood:soda'}, {'item': 'xercafood:carbonated_water'}),
    ShapelessRecipe([{'item': 'minecraft:warped_roots'}, {'item': 'minecraft:rotten_flesh'}, {'item': 'minecraft:spider_eye'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:sugar'}], {'item': 'xercafood:cola_powder'}, {'item': 'minecraft:spider_eye'}),

    ShapelessRecipe([{'item': 'xercafood:item_knife', 'data': 32767}, {'item': 'minecraft:salmon'}], {'item': 'xercafood:sashimi', 'count': 2}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'minecraft:dried_kelp'}], {'item': 'xercafood:riceball', 'count': 2}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'minecraft:dried_kelp'}, {'item': 'xercafood:sashimi'}], {'item': 'xercafood:sushi', 'count': 2}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'xercafood:sashimi'}], {'item': 'xercafood:nigiri_sushi'}, {'item': 'xercafood:cooked_rice', 'count': 2}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'xercafood:item_fried_egg'}], {'item': 'xercafood:omurice'}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'xercafood:item_fried_egg'}, {'item': 'minecraft:dried_kelp'}], {'item': 'xercafood:egg_sushi', 'count': 2}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:item_glass'}, {'item': 'xercafood:item_rice_seeds'}, {'item': 'xercafood:item_rice_seeds'}], {'item': 'xercafood:sake'}, {'item': 'xercafood:item_rice_seeds'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'minecraft:cooked_cod'}, {'item': 'minecraft:glow_ink_sac'}, {'item': 'minecraft:kelp'}, {'item': 'minecraft:bowl'}], {'item': 'xercafood:glow_squid_ink_paella'}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'minecraft:cooked_cod'}, {'item': 'minecraft:ink_sac'}, {'item': 'minecraft:kelp'}, {'item': 'minecraft:bowl'}], {'item': 'xercafood:squid_ink_paella'}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'minecraft:cooked_beef'}, {'item': 'minecraft:bowl'}], {'item': 'xercafood:beef_donburi'}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'minecraft:cooked_chicken'}, {'item': 'minecraft:bowl'}, {'item': 'xercafood:item_fried_egg'}], {'item': 'xercafood:oyakodon'}, {'item': 'xercafood:cooked_rice'}),
    ShapelessRecipe([{'item': 'xercafood:cooked_rice'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:bowl'}, {'item': 'minecraft:milk_bucket'}], {'item': 'xercafood:rice_pudding'}, {'item': 'xercafood:item_rice_seeds'}),
    ShapelessRecipe([{'item': 'xercafood:doner_slice'}, {'item': 'xercafood:item_yoghurt'}, {'item': 'xercafood:item_tomato_slices'}, {'item': 'minecraft:bread'}, {'item': 'minecraft:bowl'}], {'item': 'xercafood:item_alexander'}, {'item': 'xercafood:doner_slice'}),
    ShapelessRecipe([{'item': 'minecraft:sweet_berries'}, {'item': 'xercafood:item_yoghurt'}, {'item': 'minecraft:honey_bottle'}, {'item': 'minecraft:bowl'}], {'item': 'xercafood:item_honeyberry_yoghurt'}, {'item': 'xercafood:item_yoghurt'}),
    ShapelessRecipe([{'item': 'minecraft:mutton'}, {'item': 'minecraft:stick'}, {'item': 'xercafood:item_tomato_slices'}], {'item': 'xercafood:raw_shish_kebab'}, {'item': 'minecraft:mutton'}),

    # PIZZA RECIPES START
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:item_raw_sausage"}, {"item": "xercafood:item_raw_sausage"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_pepperoni_pepperoni_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:brown_mushroom"}, {"item": "xercafood:item_raw_sausage"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_mushroom_pepperoni_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:brown_mushroom"}, {"item": "minecraft:brown_mushroom"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_mushroom_mushroom_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:brown_mushroom"}, {"item": "minecraft:brown_mushroom"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_mushroom_mushroom_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:item_raw_sausage"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_meat_pepperoni_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "minecraft:brown_mushroom"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_meat_mushroom_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "minecraft:brown_mushroom"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_meat_mushroom_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_meat_meat_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:doner_slice"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_meat_meat_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_meat_meat_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "xercafood:item_raw_sausage"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_fish_pepperoni_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "minecraft:brown_mushroom"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_fish_mushroom_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "minecraft:brown_mushroom"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_fish_mushroom_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_fish_meat_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "xercafood:doner_slice"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_fish_meat_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_fish_meat_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "minecraft:cod"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_fish_fish_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "minecraft:cod"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_fish_fish_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "minecraft:cod"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_fish_fish_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "minecraft:cod"}, {"item": "minecraft:cod"}], {"item": "xercafood:raw_pizza_fish_fish_fish"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "xercafood:item_raw_sausage"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_chicken_pepperoni_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:brown_mushroom"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_chicken_mushroom_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:brown_mushroom"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_chicken_mushroom_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_chicken_meat_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "xercafood:doner_slice"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_chicken_meat_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_chicken_meat_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:cod"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_chicken_fish_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:cod"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_chicken_fish_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:cod"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_chicken_fish_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:cod"}, {"item": "minecraft:cod"}], {"item": "xercafood:raw_pizza_chicken_fish_fish"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:chicken"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_chicken_chicken_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:chicken"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_chicken_chicken_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:chicken"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_chicken_chicken_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:chicken"}, {"item": "minecraft:cod"}], {"item": "xercafood:raw_pizza_chicken_chicken_fish"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:chicken"}, {"item": "minecraft:chicken"}], {"item": "xercafood:raw_pizza_chicken_chicken_chicken"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:item_raw_sausage"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_pepperoni_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:brown_mushroom"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_mushroom_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:brown_mushroom"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_mushroom_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_meat_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_meat_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_meat_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_fish_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_fish_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_fish_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}, {"item": "minecraft:cod"}], {"item": "xercafood:raw_pizza_fish_fish"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_chicken_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_chicken_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_chicken_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:cod"}], {"item": "xercafood:raw_pizza_chicken_fish"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}, {"item": "minecraft:chicken"}], {"item": "xercafood:raw_pizza_chicken_chicken"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:item_raw_sausage"}], {"item": "xercafood:raw_pizza_pepperoni"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:brown_mushroom"}], {"item": "xercafood:raw_pizza_mushroom"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "xercafood:doner_slice"}], {"item": "xercafood:raw_pizza_meat"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:cod"}], {"item": "xercafood:raw_pizza_fish"}, {"item": "xercafood:raw_pizza"}, "pizza"),
    ShapelessRecipe([{"item": "xercafood:raw_pizza"}, {"item": "minecraft:chicken"}], {"item": "xercafood:raw_pizza_chicken"}, {"item": "xercafood:raw_pizza"}, "pizza"),

    # PIZZA RECIPES END
    # ShapelessRecipe([{'item': 'xercafood:pizza_dough'}, {'item': 'xercafood:item_tomato_slices'}, {'item': 'xercafood:cheese_slice'}], {'item': 'xercafood:raw_plain_pizza'}, {'item': 'xercafood:pizza_dough'}),
    # ShapelessRecipe([{'item': 'xercafood:pizza_dough'}, {'item': 'xercafood:item_tomato_slices'}, {'item': 'xercafood:cheese_slice'}, {'item': 'xercafood:item_raw_sausage'}], {'item': 'xercafood:raw_sausage_pizza'}, {'item': 'xercafood:pizza_dough'}),
    # ShapelessRecipe([{'item': 'xercafood:pizza_dough'}, {'item': 'xercafood:item_tomato_slices'}, {'item': 'xercafood:cheese_slice'}, {'item': 'minecraft:brown_mushroom'}], {'item': 'xercafood:raw_mush_pizza'}, {'item': 'xercafood:pizza_dough'}),
    # ShapelessRecipe([{'item': 'xercafood:pizza_dough'}, {'item': 'xercafood:item_tomato_slices'}, {'item': 'xercafood:cheese_slice'}, {'item': 'minecraft:red_mushroom'}], {'item': 'xercafood:raw_mush_pizza'}, {'item': 'xercafood:pizza_dough'}),
    # ShapelessRecipe([{'item': 'xercafood:pizza_dough'}, {'item': 'xercafood:item_tomato_slices'}, {'item': 'xercafood:cheese_slice'}, {'item': 'minecraft:brown_mushroom'}, {'item': 'xercafood:item_raw_sausage'}], {'item': 'xercafood:raw_mush_sausage_pizza'}, {'item': 'xercafood:pizza_dough'}),
    # ShapelessRecipe([{'item': 'xercafood:pizza_dough'}, {'item': 'xercafood:item_tomato_slices'}, {'item': 'xercafood:cheese_slice'}, {'item': 'minecraft:red_mushroom'}, {'item': 'xercafood:item_raw_sausage'}], {'item': 'xercafood:raw_mush_sausage_pizza'}, {'item': 'xercafood:pizza_dough'}),

    ShapelessRecipe([{'item': 'xercafood:item_knife', 'data': 32767}, {'item': 'minecraft:acacia_log'}], {'item': 'minecraft:stripped_acacia_log'}, {'item': 'xercafood:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_knife', 'data': 32767}, {'item': 'minecraft:birch_log'}], {'item': 'minecraft:stripped_birch_log'}, {'item': 'xercafood:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_knife', 'data': 32767}, {'item': 'minecraft:dark_oak_log'}], {'item': 'minecraft:stripped_dark_oak_log'}, {'item': 'xercafood:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_knife', 'data': 32767}, {'item': 'minecraft:jungle_log'}], {'item': 'minecraft:stripped_jungle_log'}, {'item': 'xercafood:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_knife', 'data': 32767}, {'item': 'minecraft:oak_log'}], {'item': 'minecraft:stripped_oak_log'}, {'item': 'xercafood:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercafood:item_knife', 'data': 32767}, {'item': 'minecraft:spruce_log'}], {'item': 'minecraft:stripped_spruce_log'}, {'item': 'xercafood:item_knife'}, ""),

    ShapelessRecipe([{'item': 'minecraft:string'}, {'item': 'minecraft:string'}, {'item': 'minecraft:string'}], {'item': 'xercafood:rope'}, {'item': 'minecraft:string'}, ""),
]

cooking_recipes = [
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:rice_pudding'}, "xercafood:baked_rice_pudding", 0.2, 250, {'item': 'xercafood:rice_pudding'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_raw_chicken_patty'}, "xercafood:item_cooked_chicken_patty", 0.2, 200, {'item': 'xercafood:item_raw_chicken_patty'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'minecraft:egg'}, "xercafood:item_fried_egg", 0.2, 200, {'item': 'minecraft:egg'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_raw_patty'}, "xercafood:item_cooked_patty", 0.2, 200, {'item': 'xercafood:item_raw_patty'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_potato_slices'}, "xercafood:item_potato_fries", 0.2, 200, {'item': 'xercafood:item_potato_slices'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_raw_sausage'}, "xercafood:item_cooked_sausage", 0.2, 200, {'item': 'xercafood:item_raw_sausage'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_raw_schnitzel'}, "xercafood:item_cooked_schnitzel", 0.2, 200, {'item': 'xercafood:item_raw_schnitzel'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_tea_leaf'}, "xercafood:item_tea_dried", 0.1, 200, {'item': 'xercafood:item_tea_leaf'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_full_teapot_1'}, "xercafood:item_hot_teapot_1", 0.1, 100, {'item': 'xercafood:item_full_teapot_1'}, "hot_teapot"),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_full_teapot_2'}, "xercafood:item_hot_teapot_2", 0.15, 150, {'item': 'xercafood:item_full_teapot_2'}, "hot_teapot"),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_full_teapot_3'}, "xercafood:item_hot_teapot_3", 0.2, 200, {'item': 'xercafood:item_full_teapot_3'}, "hot_teapot"),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_full_teapot_4'}, "xercafood:item_hot_teapot_4", 0.25, 250, {'item': 'xercafood:item_full_teapot_4'}, "hot_teapot"),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_full_teapot_5'}, "xercafood:item_hot_teapot_5", 0.3, 300, {'item': 'xercafood:item_full_teapot_5'}, "hot_teapot"),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_full_teapot_6'}, "xercafood:item_hot_teapot_6", 0.35, 350, {'item': 'xercafood:item_full_teapot_6'}, "hot_teapot"),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_full_teapot_7'}, "xercafood:item_hot_teapot_7", 0.4, 400, {'item': 'xercafood:item_full_teapot_7'}, "hot_teapot"),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:item_rice_seeds'}, "xercafood:cooked_rice", 0.2, 200, {'item': 'xercafood:item_rice_seeds'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'minecraft:milk_bucket'}, "xercafood:item_yoghurt", 0.2, 200, {'item': 'minecraft:milk_bucket'}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:raw_shish_kebab'}, "xercafood:item_shish_kebab", 0.2, 200, {'item': 'xercafood:raw_shish_kebab'}, ""),

    # PIZZA COOKING RECIPES START
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_pepperoni_pepperoni_pepperoni"}, "xercafood:pizza_pepperoni_pepperoni_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_pepperoni_pepperoni_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_mushroom_pepperoni_pepperoni"}, "xercafood:pizza_mushroom_pepperoni_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_mushroom_pepperoni_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_mushroom_mushroom_pepperoni"}, "xercafood:pizza_mushroom_mushroom_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_mushroom_mushroom_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_mushroom_mushroom_mushroom"}, "xercafood:pizza_mushroom_mushroom_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_mushroom_mushroom_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_pepperoni_pepperoni"}, "xercafood:pizza_meat_pepperoni_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_meat_pepperoni_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_mushroom_pepperoni"}, "xercafood:pizza_meat_mushroom_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_meat_mushroom_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_mushroom_mushroom"}, "xercafood:pizza_meat_mushroom_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_meat_mushroom_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_meat_pepperoni"}, "xercafood:pizza_meat_meat_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_meat_meat_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_meat_mushroom"}, "xercafood:pizza_meat_meat_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_meat_meat_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_meat_meat"}, "xercafood:pizza_meat_meat_meat", 0.2, 300, {"item": "xercafood:raw_pizza_meat_meat_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_pepperoni_pepperoni"}, "xercafood:pizza_fish_pepperoni_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_fish_pepperoni_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_mushroom_pepperoni"}, "xercafood:pizza_fish_mushroom_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_fish_mushroom_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_mushroom_mushroom"}, "xercafood:pizza_fish_mushroom_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_fish_mushroom_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_meat_pepperoni"}, "xercafood:pizza_fish_meat_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_fish_meat_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_meat_mushroom"}, "xercafood:pizza_fish_meat_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_fish_meat_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_meat_meat"}, "xercafood:pizza_fish_meat_meat", 0.2, 300, {"item": "xercafood:raw_pizza_fish_meat_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_fish_pepperoni"}, "xercafood:pizza_fish_fish_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_fish_fish_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_fish_mushroom"}, "xercafood:pizza_fish_fish_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_fish_fish_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_fish_meat"}, "xercafood:pizza_fish_fish_meat", 0.2, 300, {"item": "xercafood:raw_pizza_fish_fish_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_fish_fish"}, "xercafood:pizza_fish_fish_fish", 0.2, 300, {"item": "xercafood:raw_pizza_fish_fish_fish"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_pepperoni_pepperoni"}, "xercafood:pizza_chicken_pepperoni_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_pepperoni_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_mushroom_pepperoni"}, "xercafood:pizza_chicken_mushroom_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_mushroom_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_mushroom_mushroom"}, "xercafood:pizza_chicken_mushroom_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_mushroom_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_meat_pepperoni"}, "xercafood:pizza_chicken_meat_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_meat_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_meat_mushroom"}, "xercafood:pizza_chicken_meat_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_meat_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_meat_meat"}, "xercafood:pizza_chicken_meat_meat", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_meat_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_fish_pepperoni"}, "xercafood:pizza_chicken_fish_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_fish_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_fish_mushroom"}, "xercafood:pizza_chicken_fish_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_fish_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_fish_meat"}, "xercafood:pizza_chicken_fish_meat", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_fish_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_fish_fish"}, "xercafood:pizza_chicken_fish_fish", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_fish_fish"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_chicken_pepperoni"}, "xercafood:pizza_chicken_chicken_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_chicken_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_chicken_mushroom"}, "xercafood:pizza_chicken_chicken_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_chicken_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_chicken_meat"}, "xercafood:pizza_chicken_chicken_meat", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_chicken_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_chicken_fish"}, "xercafood:pizza_chicken_chicken_fish", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_chicken_fish"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_chicken_chicken"}, "xercafood:pizza_chicken_chicken_chicken", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_chicken_chicken"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_pepperoni_pepperoni"}, "xercafood:pizza_pepperoni_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_pepperoni_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_mushroom_pepperoni"}, "xercafood:pizza_mushroom_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_mushroom_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_mushroom_mushroom"}, "xercafood:pizza_mushroom_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_mushroom_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_pepperoni"}, "xercafood:pizza_meat_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_meat_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_mushroom"}, "xercafood:pizza_meat_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_meat_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat_meat"}, "xercafood:pizza_meat_meat", 0.2, 300, {"item": "xercafood:raw_pizza_meat_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_pepperoni"}, "xercafood:pizza_fish_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_fish_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_mushroom"}, "xercafood:pizza_fish_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_fish_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_meat"}, "xercafood:pizza_fish_meat", 0.2, 300, {"item": "xercafood:raw_pizza_fish_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish_fish"}, "xercafood:pizza_fish_fish", 0.2, 300, {"item": "xercafood:raw_pizza_fish_fish"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_pepperoni"}, "xercafood:pizza_chicken_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_mushroom"}, "xercafood:pizza_chicken_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_meat"}, "xercafood:pizza_chicken_meat", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_fish"}, "xercafood:pizza_chicken_fish", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_fish"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken_chicken"}, "xercafood:pizza_chicken_chicken", 0.2, 300, {"item": "xercafood:raw_pizza_chicken_chicken"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_pepperoni"}, "xercafood:pizza_pepperoni", 0.2, 300, {"item": "xercafood:raw_pizza_pepperoni"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_mushroom"}, "xercafood:pizza_mushroom", 0.2, 300, {"item": "xercafood:raw_pizza_mushroom"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_meat"}, "xercafood:pizza_meat", 0.2, 300, {"item": "xercafood:raw_pizza_meat"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_fish"}, "xercafood:pizza_fish", 0.2, 300, {"item": "xercafood:raw_pizza_fish"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza_chicken"}, "xercafood:pizza_chicken", 0.2, 300, {"item": "xercafood:raw_pizza_chicken"}, ""),
    CookingRecipe("xercafood:crafting_condition_smelting_food", {"item": "xercafood:raw_pizza"}, "xercafood:pizza", 0.2, 300, {"item": "xercafood:raw_pizza"}, ""),

    # CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:raw_plain_pizza'}, "xercafood:plain_pizza", 0.2, 300, {'item': 'xercafood:raw_plain_pizza'}, ""),
    # CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:raw_sausage_pizza'}, "xercafood:sausage_pizza", 0.2, 350, {'item': 'xercafood:raw_sausage_pizza'}, ""),
    # CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:raw_mush_pizza'}, "xercafood:mush_pizza", 0.2, 350, {'item': 'xercafood:raw_mush_pizza'}, ""),
    # CookingRecipe("xercafood:crafting_condition_smelting_food", {'item': 'xercafood:raw_mush_sausage_pizza'}, "xercafood:mush_sausage_pizza", 0.2, 400, {'item': 'xercafood:raw_mush_sausage_pizza'}, ""),

    # PIZZA COOKING RECIPES END
]

special_recipes = [
    SpecialRecipe("xercafood:crafting_special_flask_filling", None, ""),
    SpecialRecipe("xercafood:crafting_special_ender_bow_filling", None, ""),
    SpecialRecipe("xercafood:crafting_special_flask_milk_filling", None, ""),
    SpecialRecipe("xercafood:crafting_special_tea_filling", None, ""),
    SpecialRecipe("xercafood:crafting_special_tea_pouring", None, ""),
    SpecialRecipe("xercafood:crafting_special_tea_refilling", None, ""),
    SpecialRecipe("xercafood:crafting_special_tea_sugaring", None, ""),
    SpecialRecipe("xercafood:crafting_special_wood_carving", None, ""),
]

stonecutting_recipes = [
    StonecuttingRecipe("xercablocks:black_terratile", "xercablocks:black_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:blue_terratile", "xercablocks:blue_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:brown_terratile", "xercablocks:brown_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:cyan_terratile", "xercablocks:cyan_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:gray_terratile", "xercablocks:gray_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:green_terratile", "xercablocks:green_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:light_blue_terratile", "xercablocks:light_blue_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:light_gray_terratile", "xercablocks:light_gray_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:lime_terratile", "xercablocks:lime_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:magenta_terratile", "xercablocks:magenta_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:orange_terratile", "xercablocks:orange_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:pink_terratile", "xercablocks:pink_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:purple_terratile", "xercablocks:purple_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:red_terratile", "xercablocks:red_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:white_terratile", "xercablocks:white_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:yellow_terratile", "xercablocks:yellow_terratile_slab", 2, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:terratile", "xercablocks:terratile_slab", 2, "", "terracotta_tile"),

    StonecuttingRecipe("xercablocks:black_terratile", "xercablocks:black_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:blue_terratile", "xercablocks:blue_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:brown_terratile", "xercablocks:brown_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:cyan_terratile", "xercablocks:cyan_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:gray_terratile", "xercablocks:gray_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:green_terratile", "xercablocks:green_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:light_blue_terratile", "xercablocks:light_blue_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:light_gray_terratile", "xercablocks:light_gray_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:lime_terratile", "xercablocks:lime_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:magenta_terratile", "xercablocks:magenta_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:orange_terratile", "xercablocks:orange_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:pink_terratile", "xercablocks:pink_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:purple_terratile", "xercablocks:purple_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:red_terratile", "xercablocks:red_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:white_terratile", "xercablocks:white_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:yellow_terratile", "xercablocks:yellow_terratile_stairs", 1, "", "terracotta_tile"),
    StonecuttingRecipe("xercablocks:terratile", "xercablocks:terratile_stairs", 1, "", "terracotta_tile"),

    StonecuttingRecipe("minecraft:black_terracotta", "xercablocks:black_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:blue_terracotta", "xercablocks:blue_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:brown_terracotta", "xercablocks:brown_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:cyan_terracotta", "xercablocks:cyan_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:gray_terracotta", "xercablocks:gray_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:green_terracotta", "xercablocks:green_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:light_blue_terracotta", "xercablocks:light_blue_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:light_gray_terracotta", "xercablocks:light_gray_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:lime_terracotta", "xercablocks:lime_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:magenta_terracotta", "xercablocks:magenta_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:orange_terracotta", "xercablocks:orange_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:pink_terracotta", "xercablocks:pink_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:purple_terracotta", "xercablocks:purple_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:red_terracotta", "xercablocks:red_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:white_terracotta", "xercablocks:white_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:yellow_terracotta", "xercablocks:yellow_terratile", 1, "", "terracotta_tile"),
    StonecuttingRecipe("minecraft:terracotta", "xercablocks:terratile", 1, "", "terracotta_tile"),
]

carving_recipes = [
    CarvingRecipe("minecraft:oak_log", "minecraft:stripped_oak_log", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercablocks:carved_oak_1", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercablocks:carved_oak_2", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercablocks:carved_oak_3", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercablocks:carved_oak_4", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercablocks:carved_oak_5", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercablocks:carved_oak_6", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercablocks:carved_oak_7", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercablocks:carved_oak_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercablocks:carved_oak_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercablocks:carved_oak_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercablocks:carved_oak_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercablocks:carved_oak_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercablocks:carved_oak_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercablocks:carved_oak_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercablocks:carved_oak_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercablocks:carved_oak_8", 1, "", "carving"),

    CarvingRecipe("minecraft:birch_log", "minecraft:stripped_birch_log", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercablocks:carved_birch_1", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercablocks:carved_birch_2", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercablocks:carved_birch_3", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercablocks:carved_birch_4", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercablocks:carved_birch_5", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercablocks:carved_birch_6", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercablocks:carved_birch_7", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercablocks:carved_birch_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercablocks:carved_birch_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercablocks:carved_birch_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercablocks:carved_birch_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercablocks:carved_birch_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercablocks:carved_birch_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercablocks:carved_birch_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercablocks:carved_birch_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercablocks:carved_birch_8", 1, "", "carving"),

    CarvingRecipe("minecraft:spruce_log", "minecraft:stripped_spruce_log", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercablocks:carved_spruce_1", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercablocks:carved_spruce_2", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercablocks:carved_spruce_3", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercablocks:carved_spruce_4", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercablocks:carved_spruce_5", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercablocks:carved_spruce_6", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercablocks:carved_spruce_7", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercablocks:carved_spruce_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercablocks:carved_spruce_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercablocks:carved_spruce_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercablocks:carved_spruce_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercablocks:carved_spruce_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercablocks:carved_spruce_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercablocks:carved_spruce_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercablocks:carved_spruce_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercablocks:carved_spruce_8", 1, "", "carving"),

    CarvingRecipe("minecraft:jungle_log", "minecraft:stripped_jungle_log", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercablocks:carved_jungle_1", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercablocks:carved_jungle_2", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercablocks:carved_jungle_3", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercablocks:carved_jungle_4", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercablocks:carved_jungle_5", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercablocks:carved_jungle_6", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercablocks:carved_jungle_7", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercablocks:carved_jungle_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercablocks:carved_jungle_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercablocks:carved_jungle_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercablocks:carved_jungle_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercablocks:carved_jungle_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercablocks:carved_jungle_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercablocks:carved_jungle_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercablocks:carved_jungle_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercablocks:carved_jungle_8", 1, "", "carving"),

    CarvingRecipe("minecraft:acacia_log", "minecraft:stripped_acacia_log", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercablocks:carved_acacia_1", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercablocks:carved_acacia_2", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercablocks:carved_acacia_3", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercablocks:carved_acacia_4", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercablocks:carved_acacia_5", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercablocks:carved_acacia_6", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercablocks:carved_acacia_7", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercablocks:carved_acacia_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercablocks:carved_acacia_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercablocks:carved_acacia_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercablocks:carved_acacia_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercablocks:carved_acacia_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercablocks:carved_acacia_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercablocks:carved_acacia_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercablocks:carved_acacia_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercablocks:carved_acacia_8", 1, "", "carving"),

    CarvingRecipe("minecraft:dark_oak_log", "minecraft:stripped_dark_oak_log", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercablocks:carved_dark_oak_1", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercablocks:carved_dark_oak_2", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercablocks:carved_dark_oak_3", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercablocks:carved_dark_oak_4", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercablocks:carved_dark_oak_5", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercablocks:carved_dark_oak_6", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercablocks:carved_dark_oak_7", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercablocks:carved_dark_oak_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercablocks:carved_dark_oak_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercablocks:carved_dark_oak_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercablocks:carved_dark_oak_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercablocks:carved_dark_oak_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercablocks:carved_dark_oak_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercablocks:carved_dark_oak_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercablocks:carved_dark_oak_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercablocks:carved_dark_oak_8", 1, "", "carving"),

    CarvingRecipe("minecraft:crimson_stem", "minecraft:stripped_crimson_stem", 1, "", "carving"),
    CarvingRecipe("minecraft:crimson_stem", "xercablocks:carved_crimson_1", 1, "", "carving"),
    CarvingRecipe("minecraft:crimson_stem", "xercablocks:carved_crimson_2", 1, "", "carving"),
    CarvingRecipe("minecraft:crimson_stem", "xercablocks:carved_crimson_3", 1, "", "carving"),
    CarvingRecipe("minecraft:crimson_stem", "xercablocks:carved_crimson_4", 1, "", "carving"),
    CarvingRecipe("minecraft:crimson_stem", "xercablocks:carved_crimson_5", 1, "", "carving"),
    CarvingRecipe("minecraft:crimson_stem", "xercablocks:carved_crimson_6", 1, "", "carving"),
    CarvingRecipe("minecraft:crimson_stem", "xercablocks:carved_crimson_7", 1, "", "carving"),
    CarvingRecipe("minecraft:crimson_stem", "xercablocks:carved_crimson_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_crimson_stem", "xercablocks:carved_crimson_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_crimson_stem", "xercablocks:carved_crimson_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_crimson_stem", "xercablocks:carved_crimson_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_crimson_stem", "xercablocks:carved_crimson_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_crimson_stem", "xercablocks:carved_crimson_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_crimson_stem", "xercablocks:carved_crimson_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_crimson_stem", "xercablocks:carved_crimson_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_crimson_stem", "xercablocks:carved_crimson_8", 1, "", "carving"),

    CarvingRecipe("minecraft:warped_stem", "minecraft:stripped_warped_stem", 1, "", "carving"),
    CarvingRecipe("minecraft:warped_stem", "xercablocks:carved_warped_1", 1, "", "carving"),
    CarvingRecipe("minecraft:warped_stem", "xercablocks:carved_warped_2", 1, "", "carving"),
    CarvingRecipe("minecraft:warped_stem", "xercablocks:carved_warped_3", 1, "", "carving"),
    CarvingRecipe("minecraft:warped_stem", "xercablocks:carved_warped_4", 1, "", "carving"),
    CarvingRecipe("minecraft:warped_stem", "xercablocks:carved_warped_5", 1, "", "carving"),
    CarvingRecipe("minecraft:warped_stem", "xercablocks:carved_warped_6", 1, "", "carving"),
    CarvingRecipe("minecraft:warped_stem", "xercablocks:carved_warped_7", 1, "", "carving"),
    CarvingRecipe("minecraft:warped_stem", "xercablocks:carved_warped_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_warped_stem", "xercablocks:carved_warped_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_warped_stem", "xercablocks:carved_warped_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_warped_stem", "xercablocks:carved_warped_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_warped_stem", "xercablocks:carved_warped_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_warped_stem", "xercablocks:carved_warped_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_warped_stem", "xercablocks:carved_warped_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_warped_stem", "xercablocks:carved_warped_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_warped_stem", "xercablocks:carved_warped_8", 1, "", "carving"),
]

smithing_recipes = [
    SmithingRecipe("xercafood:diamond_scythe", "minecraft:netherite_ingot", "xercafood:netherite_scythe"),
    SmithingRecipe("xercafood:item_diamond_warhammer", "minecraft:netherite_ingot", "xercafood:item_netherite_warhammer")
]

campfire_recipes = []
smoker_recipes = []

for r in cooking_recipes:
    campfire_recipe = deepcopy(r)
    campfire_recipe.type = "xercafood:crafting_condition_campfire_food"
    campfire_recipe.cooking_time *= 3
    campfire_recipes.append(campfire_recipe)

    smoker_recipe = deepcopy(r)
    smoker_recipe.type = "xercafood:crafting_condition_smoking_food"
    smoker_recipe.cooking_time = int(smoker_recipe.cooking_time*0.5)
    smoker_recipes.append(smoker_recipe)

all_recipes = [r for l in [shaped_recipes, shapeless_recipes, cooking_recipes, special_recipes, campfire_recipes, smoker_recipes, stonecutting_recipes, carving_recipes, smithing_recipes] for r in l]


# generate_recipe_code_from_files("xercafood")
clean_recipe_jsons("xercafood")
generate_recipe_jsons(all_recipes, "xercafood")
