from copy import deepcopy

from recipe_generator import *

shaped_recipes = [
    ShapedRecipe([' l ', 'lel', ' l '], {'item': 'xercamod:flask'}, {'e': {'item': 'minecraft:ender_eye'}, 'l': {'item': 'minecraft:leather'}}, {'item': 'minecraft:ender_eye'}, "", type="xercamod:crafting_condition_shaped_ender_flask"),
    ShapedRecipe(['www', 'mem', 'sas'], {'item': 'xercamod:ender_cupcake', 'count': 6}, {'a': {'item': 'minecraft:chorus_fruit'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:chorus_fruit'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['sas', 'mem', 'www'], {'item': 'xercamod:item_honey_cupcake', 'count': 6}, {'a': {'item': 'minecraft:honey_bottle'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:honey_bottle'}, "cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['sas', 'mem', 'www'], {'item': 'xercamod:sweet_berry_cupcake', 'count': 6}, {'a': {'item': 'minecraft:sweet_berries'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:sweet_berries'}, "cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['sas', 'mem', 'www'], {'item': 'xercamod:item_apple_cupcake', 'count': 6}, {'a': {'item': 'minecraft:apple'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:apple'}, "cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['ADA', 'BEB', 'CCC'], {'item': 'xercamod:sweet_berry_pie'}, {'A': {'item': 'minecraft:sweet_berries'}, 'B': {'item': 'minecraft:sugar'}, 'C': {'item': 'minecraft:wheat'}, 'D': {'item': 'minecraft:milk_bucket'}, 'E': {'item': 'minecraft:egg'}}, {'item': 'minecraft:sweet_berries'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['ADA', 'BEB', 'CCC'], {'item': 'xercamod:item_apple_pie'}, {'A': {'item': 'minecraft:apple'}, 'B': {'item': 'minecraft:sugar'}, 'C': {'item': 'minecraft:wheat'}, 'D': {'item': 'minecraft:milk_bucket'}, 'E': {'item': 'minecraft:egg'}}, {'item': 'minecraft:apple'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['lll', 'lll', 'lll'], {'item': 'xercamod:item_block_leather'}, {'l': {'item': 'minecraft:leather'}}, {'item': 'minecraft:leather'}, "", type="xercamod:crafting_condition_shaped_leather_straw"),
    ShapedRecipe(['lll', 'lll', 'lll'], {'item': 'xercamod:item_block_straw'}, {'l': {'item': 'minecraft:sugar_cane'}}, {'item': 'minecraft:sugar_cane'}, "", type="xercamod:crafting_condition_shaped_leather_straw"),
    ShapedRecipe(['www', '   ', 'www'], {'item': 'xercamod:item_bookcase'}, {'w': {'tag': 'minecraft:planks'}}, {'tag': 'minecraft:planks'}, "", type="xercamod:crafting_condition_shaped_bookcase"),
    ShapedRecipe(['sas', 'mem', 'www'], {'item': 'xercamod:item_carrot_cupcake', 'count': 6}, {'a': {'item': 'minecraft:carrot'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:carrot'}, "cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' b ', 'dc ', ' b '], {'item': 'xercamod:item_chicken_burger'}, {'b': {'item': 'xercamod:item_bun'}, 'c': {'item': 'xercamod:item_cooked_chicken_patty'}, 'd': {'item': 'xercamod:item_tomato_slices'}}, {'item': 'xercamod:item_bun'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' wc', 'wcw', 'cw '], {'item': 'xercamod:item_chicken_wrap', 'count': 4}, {'c': {'item': 'minecraft:cooked_chicken'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'minecraft:cooked_chicken'}, "chicken_wrap", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['cw ', 'wcw', ' wc'], {'item': 'xercamod:item_chicken_wrap', 'count': 4}, {'c': {'item': 'minecraft:cooked_chicken'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'minecraft:cooked_chicken'}, "chicken_wrap", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' s ', 'cmc', ' s '], {'item': 'xercamod:item_chocolate', 'count': 6}, {'s': {'item': 'minecraft:sugar'}, 'c': {'item': 'minecraft:cocoa_beans'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:cocoa_beans'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['sps', 'mem', 'www'], {'item': 'xercamod:item_cocoa_cupcake', 'count': 6}, {'p': {'item': 'minecraft:cocoa_beans'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:cocoa_beans'}, "cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' c ', 'cgc', ' c '], {'item': 'xercamod:item_confetti_ball', 'count': 2}, {'c': {'item': 'xercamod:item_confetti'}, 'g': {'item': 'minecraft:gunpowder'}}, {'item': 'xercamod:item_confetti'}, "", type="xercamod:crafting_condition_shaped_confetti"),
    ShapedRecipe(['sws', 'www'], {'item': 'xercamod:item_croissant', 'count': 2}, {'s': {'item': 'minecraft:sugar'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'minecraft:wheat'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' b ', 'yyy', ' b '], {'item': 'xercamod:item_daisy_sandwich', 'count': 3}, {'b': {'item': 'minecraft:bread'}, 'y': {'item': 'minecraft:oxeye_daisy'}}, {'item': 'minecraft:oxeye_daisy'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['tst', ' s ', ' s '], {'item': 'xercamod:item_diamond_warhammer'}, {'s': {'item': 'minecraft:stick'}, 't': {'item': 'minecraft:diamond'}}, {'item': 'minecraft:diamond'}, "", type="xercamod:crafting_condition_shaped_warhammer"),
    ShapedRecipe(['sws', 'wxw', 'sws'], {'item': 'xercamod:item_donut', 'count': 4}, {'s': {'item': 'minecraft:sugar'}, 'w': {'item': 'minecraft:wheat'}, 'x': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:wheat'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['s', 'c'], {'item': 'xercamod:sweet_berry_cupcake_fancy'}, {'s': {'item': 'xercamod:item_sprinkles'}, 'c': {'item': 'xercamod:sweet_berry_cupcake'}}, {'item': 'xercamod:item_sprinkles'}, "fancy_cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['s', 'c'], {'item': 'xercamod:item_fancy_apple_cupcake'}, {'s': {'item': 'xercamod:item_sprinkles'}, 'c': {'item': 'xercamod:item_apple_cupcake'}}, {'item': 'xercamod:item_sprinkles'}, "fancy_cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['s', 'd'], {'item': 'xercamod:item_fancy_donut'}, {'s': {'item': 'xercamod:item_sprinkles'}, 'd': {'item': 'xercamod:item_donut'}}, {'item': 'xercamod:item_sprinkles'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['s', 'c'], {'item': 'xercamod:item_fancy_pumpkin_cupcake'}, {'s': {'item': 'xercamod:item_sprinkles'}, 'c': {'item': 'xercamod:item_pumpkin_cupcake'}}, {'item': 'xercamod:item_sprinkles'}, "fancy_cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['b', 'h', 'b'], {'item': 'xercamod:item_fish_bread', 'count': 2}, {'b': {'item': 'minecraft:bread'}, 'h': {'item': 'minecraft:cooked_cod'}}, {'item': 'minecraft:cooked_cod'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['#s#', ' s ', ' s '], {'item': 'xercamod:item_gavel'}, {'#': {'tag': 'minecraft:planks'}, 's': {'item': 'minecraft:stick'}}, {'tag': 'minecraft:planks'}, "", type="xercamod:crafting_condition_shaped_courtroom"),
    ShapedRecipe(['c c', ' c '], {'item': 'xercamod:item_glass', 'count': 3}, {'c': {'item': 'minecraft:glass_pane'}}, {'item': 'minecraft:glass_pane'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['nan', 'mem', 'www'], {'item': 'xercamod:item_golden_cupcake'}, {'a': {'item': 'minecraft:golden_apple', 'data': 0}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}, 'n': {'item': 'minecraft:gold_nugget'}}, None, ""),
    ShapedRecipe(['tst', ' s ', ' s '], {'item': 'xercamod:item_gold_warhammer'}, {'s': {'item': 'minecraft:stick'}, 't': {'item': 'minecraft:gold_ingot'}}, {'item': 'minecraft:gold_ingot'}, "", type="xercamod:crafting_condition_shaped_warhammer"),
    ShapedRecipe([' b ', 'dh ', ' b '], {'item': 'xercamod:item_hamburger'}, {'b': {'item': 'xercamod:item_bun'}, 'd': {'item': 'xercamod:item_tomato_slices'}, 'h': {'item': 'xercamod:item_cooked_patty'}}, {'item': 'xercamod:item_bun'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['b', 'p', 'b'], {'item': 'xercamod:item_hotdog'}, {'p': {'item': 'xercamod:item_cooked_sausage'}, 'b': {'item': 'xercamod:item_bun'}}, {'item': 'xercamod:item_bun'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['tst', ' s ', ' s '], {'item': 'xercamod:item_iron_warhammer'}, {'s': {'item': 'minecraft:stick'}, 't': {'item': 'minecraft:iron_ingot'}}, {'item': 'minecraft:iron_ingot'}, "", type="xercamod:crafting_condition_shaped_warhammer"),
    ShapedRecipe(['i', 's'], {'item': 'xercamod:item_knife'}, {'s': {'item': 'minecraft:stick'}, 'i': {'item': 'minecraft:iron_ingot'}}, {'item': 'minecraft:iron_ingot'}, ""),
    ShapedRecipe(['sps', 'mem', 'www'], {'item': 'xercamod:item_melon_cupcake', 'count': 6}, {'p': {'item': 'minecraft:melon'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:melon'}, "cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' b ', 'dmn', ' b '], {'item': 'xercamod:item_mushroom_burger'}, {'b': {'item': 'xercamod:item_bun'}, 'd': {'item': 'xercamod:item_tomato_slices'}, 'm': {'item': 'minecraft:brown_mushroom'}, 'n': {'item': 'minecraft:red_mushroom'}}, {'item': 'xercamod:item_bun'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['sps', 'mem', 'www'], {'item': 'xercamod:item_pumpkin_cupcake', 'count': 6}, {'p': {'item': 'minecraft:pumpkin'}, 's': {'item': 'minecraft:sugar'}, 'e': {'item': 'minecraft:egg'}, 'w': {'item': 'minecraft:wheat'}, 'm': {'item': 'minecraft:milk_bucket'}}, {'item': 'minecraft:pumpkin'}, "cupcake", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' w ', 'wcw', ' w '], {'item': 'xercamod:item_raw_schnitzel', 'count': 2}, {'c': {'item': 'minecraft:chicken'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'minecraft:chicken'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['b', 'r', 'b'], {'item': 'xercamod:item_rotten_burger'}, {'b': {'item': 'xercamod:item_bun'}, 'r': {'item': 'minecraft:rotten_flesh'}}, {'item': 'xercamod:item_bun'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['tst', ' s ', ' s '], {'item': 'xercamod:item_stone_warhammer'}, {'s': {'item': 'minecraft:stick'}, 't': {'item': 'minecraft:cobblestone'}}, {'item': 'minecraft:cobblestone'}, "", type="xercamod:crafting_condition_shaped_warhammer"),
    ShapedRecipe(['c c', ' c '], {'item': 'xercamod:item_teacup', 'count': 2}, {'c': {'item': 'minecraft:clay_ball'}}, {'item': 'minecraft:clay_ball'}, "", type="xercamod:crafting_condition_shaped_tea"),
    ShapedRecipe([' c ', 'c c', 'ccc'], {'item': 'xercamod:item_teapot'}, {'c': {'item': 'minecraft:clay_ball'}}, {'item': 'minecraft:clay_ball'}, "", type="xercamod:crafting_condition_shaped_tea"),
    ShapedRecipe(['mnm', ' p ', ' b '], {'item': 'xercamod:item_ultimate_bottom'}, {'p': {'item': 'xercamod:item_cooked_patty'}, 'b': {'item': 'xercamod:item_bun'}, 'm': {'item': 'minecraft:brown_mushroom'}, 'n': {'item': 'minecraft:red_mushroom'}}, {'item': 'xercamod:item_bun'}, "ultimate_bottom", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['nmn', ' p ', ' b '], {'item': 'xercamod:item_ultimate_bottom'}, {'p': {'item': 'xercamod:item_cooked_patty'}, 'b': {'item': 'xercamod:item_bun'}, 'm': {'item': 'minecraft:brown_mushroom'}, 'n': {'item': 'minecraft:red_mushroom'}}, {'item': 'xercamod:item_bun'}, "ultimate_bottom", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' t ', ' e ', ' b '], {'item': 'xercamod:item_ultimate_burger'}, {'b': {'item': 'xercamod:item_ultimate_bottom'}, 't': {'item': 'xercamod:item_ultimate_top'}, 'e': {'item': 'xercamod:item_bun'}}, {'item': 'xercamod:item_bun'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' b ', 'ttt', ' c '], {'item': 'xercamod:item_ultimate_top'}, {'b': {'item': 'xercamod:item_bun'}, 'c': {'item': 'xercamod:item_cooked_chicken_patty'}, 't': {'item': 'xercamod:item_tomato_slices'}}, {'item': 'xercamod:item_bun'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' wd', 'wdw', 'dw '], {'item': 'xercamod:item_doner_wrap', 'count': 4}, {'d': {'item': 'xercamod:doner_slice'}, 'w': {'item': 'minecraft:wheat'}}, {'item': 'xercamod:doner_slice'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe([' b ', 'tdp', ' b '], {'item': 'xercamod:item_chubby_doner'}, {'b': {'item': 'xercamod:item_bun'}, 't': {'item': 'xercamod:item_tomato_slices'}, 'd': {'item': 'xercamod:doner_slice'}, 'p': {'item': 'xercamod:item_potato_fries'}}, {'item': 'xercamod:doner_slice'}, "", type="xercamod:crafting_condition_shaped_food"),
    ShapedRecipe(['iis', ' s ', 's  '], {'item': 'xercamod:wooden_scythe'}, {'i': {'tag': 'minecraft:planks'}, 's': {'item': 'minecraft:stick'}}, {'tag': 'minecraft:planks'}, "xercamod:crafting_condition_shaped_scythe"),
    ShapedRecipe(['iis', ' s ', 's  '], {'item': 'xercamod:stone_scythe'}, {'i': {'item': 'minecraft:cobblestone'}, 's': {'item': 'minecraft:stick'}}, {'item': 'minecraft:cobblestone'}, "xercamod:crafting_condition_shaped_scythe"),
    ShapedRecipe(['iis', ' s ', 's  '], {'item': 'xercamod:iron_scythe'}, {'i': {'item': 'minecraft:iron_ingot'}, 's': {'item': 'minecraft:stick'}}, {'item': 'minecraft:iron_ingot'}, "xercamod:crafting_condition_shaped_scythe"),
    ShapedRecipe(['iis', ' s ', 's  '], {'item': 'xercamod:golden_scythe'}, {'i': {'item': 'minecraft:gold_ingot'}, 's': {'item': 'minecraft:stick'}}, {'item': 'minecraft:gold_ingot'}, "xercamod:crafting_condition_shaped_scythe"),
    ShapedRecipe(['iis', ' s ', 's  '], {'item': 'xercamod:diamond_scythe'}, {'i': {'item': 'minecraft:diamond'}, 's': {'item': 'minecraft:stick'}}, {'item': 'minecraft:diamond'}, "xercamod:crafting_condition_shaped_scythe"),
    ShapedRecipe([' ip', 'ipi', 'pi '], {'item': 'xercamod:spyglass'}, {'i': {'item': 'minecraft:gold_ingot'}, 'p': {'item': 'minecraft:glass_pane'}}, {'item': 'minecraft:gold_ingot'}, "xercamod:crafting_condition_shaped_spyglass"),


    # Cushion
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:black_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:black_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:blue_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:blue_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:brown_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:brown_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:cyan_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:cyan_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:gray_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:gray_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:green_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:green_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:light_blue_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:light_blue_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:light_gray_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:light_gray_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:lime_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:lime_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:magenta_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:magenta_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:orange_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:orange_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:pink_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:pink_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:purple_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:purple_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:red_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:red_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:white_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:white_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),
    ShapedRecipe(['#', 'f', '#'], {'item': 'xercamod:yellow_cushion', 'count': 1}, {'f': {'item': 'minecraft:feather'}, '#': {'item': 'minecraft:yellow_wool'}}, {'item': 'minecraft:feather'}, "cushion", "cushion", type="xercamod:crafting_condition_shaped_cushion"),

    # Terracotta tiles
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:black_terratile', 'count': 4}, {'t': {'item': 'minecraft:black_terracotta'}}, {'item': 'minecraft:black_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:blue_terratile', 'count': 4}, {'t': {'item': 'minecraft:blue_terracotta'}}, {'item': 'minecraft:blue_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:brown_terratile', 'count': 4}, {'t': {'item': 'minecraft:brown_terracotta'}}, {'item': 'minecraft:brown_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:cyan_terratile', 'count': 4}, {'t': {'item': 'minecraft:cyan_terracotta'}}, {'item': 'minecraft:cyan_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:gray_terratile', 'count': 4}, {'t': {'item': 'minecraft:gray_terracotta'}}, {'item': 'minecraft:gray_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:green_terratile', 'count': 4}, {'t': {'item': 'minecraft:green_terracotta'}}, {'item': 'minecraft:green_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:light_blue_terratile', 'count': 4}, {'t': {'item': 'minecraft:light_blue_terracotta'}}, {'item': 'minecraft:light_blue_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:light_gray_terratile', 'count': 4}, {'t': {'item': 'minecraft:light_gray_terracotta'}}, {'item': 'minecraft:light_gray_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:lime_terratile', 'count': 4}, {'t': {'item': 'minecraft:lime_terracotta'}}, {'item': 'minecraft:lime_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:magenta_terratile', 'count': 4}, {'t': {'item': 'minecraft:magenta_terracotta'}}, {'item': 'minecraft:magenta_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:orange_terratile', 'count': 4}, {'t': {'item': 'minecraft:orange_terracotta'}}, {'item': 'minecraft:orange_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:pink_terratile', 'count': 4}, {'t': {'item': 'minecraft:pink_terracotta'}}, {'item': 'minecraft:pink_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:purple_terratile', 'count': 4}, {'t': {'item': 'minecraft:purple_terracotta'}}, {'item': 'minecraft:purple_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:red_terratile', 'count': 4}, {'t': {'item': 'minecraft:red_terracotta'}}, {'item': 'minecraft:red_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:white_terratile', 'count': 4}, {'t': {'item': 'minecraft:white_terracotta'}}, {'item': 'minecraft:white_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:yellow_terratile', 'count': 4}, {'t': {'item': 'minecraft:yellow_terracotta'}}, {'item': 'minecraft:yellow_terracotta'}, "terratile", "terratile"),
    ShapedRecipe(['tt', 'tt'], {'item': 'xercamod:terratile', 'count': 4}, {'t': {'item': 'minecraft:terracotta'}}, {'item': 'minecraft:terracotta'}, "terratile", "terratile"),

    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:black_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:black_terratile'}}, {'item': 'xercamod:black_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:blue_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:blue_terratile'}}, {'item': 'xercamod:blue_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:brown_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:brown_terratile'}}, {'item': 'xercamod:brown_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:cyan_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:cyan_terratile'}}, {'item': 'xercamod:cyan_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:gray_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:gray_terratile'}}, {'item': 'xercamod:gray_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:green_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:green_terratile'}}, {'item': 'xercamod:green_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:light_blue_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:light_blue_terratile'}}, {'item': 'xercamod:light_blue_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:light_gray_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:light_gray_terratile'}}, {'item': 'xercamod:light_gray_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:lime_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:lime_terratile'}}, {'item': 'xercamod:lime_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:magenta_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:magenta_terratile'}}, {'item': 'xercamod:magenta_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:orange_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:orange_terratile'}}, {'item': 'xercamod:orange_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:pink_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:pink_terratile'}}, {'item': 'xercamod:pink_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:purple_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:purple_terratile'}}, {'item': 'xercamod:purple_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:red_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:red_terratile'}}, {'item': 'xercamod:red_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:white_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:white_terratile'}}, {'item': 'xercamod:white_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:yellow_terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:yellow_terratile'}}, {'item': 'xercamod:yellow_terratile'}, "", "terratile"),
    ShapedRecipe(['t  ', 'tt ', 'ttt'], {'item': 'xercamod:terratile_stairs', 'count': 4}, {'t': {'item': 'xercamod:terratile'}}, {'item': 'xercamod:terratile'}, "", "terratile"),

    ShapedRecipe(['ttt'], {'item': 'xercamod:black_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:black_terratile'}}, {'item': 'xercamod:black_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:blue_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:blue_terratile'}}, {'item': 'xercamod:blue_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:brown_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:brown_terratile'}}, {'item': 'xercamod:brown_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:cyan_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:cyan_terratile'}}, {'item': 'xercamod:cyan_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:gray_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:gray_terratile'}}, {'item': 'xercamod:gray_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:green_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:green_terratile'}}, {'item': 'xercamod:green_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:light_blue_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:light_blue_terratile'}}, {'item': 'xercamod:light_blue_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:light_gray_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:light_gray_terratile'}}, {'item': 'xercamod:light_gray_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:lime_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:lime_terratile'}}, {'item': 'xercamod:lime_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:magenta_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:magenta_terratile'}}, {'item': 'xercamod:magenta_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:orange_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:orange_terratile'}}, {'item': 'xercamod:orange_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:pink_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:pink_terratile'}}, {'item': 'xercamod:pink_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:purple_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:purple_terratile'}}, {'item': 'xercamod:purple_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:red_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:red_terratile'}}, {'item': 'xercamod:red_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:white_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:white_terratile'}}, {'item': 'xercamod:white_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:yellow_terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:yellow_terratile'}}, {'item': 'xercamod:yellow_terratile'}, "", "terratile"),
    ShapedRecipe(['ttt'], {'item': 'xercamod:terratile_slab', 'count': 6}, {'t': {'item': 'xercamod:terratile'}}, {'item': 'xercamod:terratile'}, "", "terratile"),

    ShapedRecipe(['f', 'c'], {'item': 'xercamod:ender_bow'},  {'c': {'item': 'minecraft:crossbow'}, 'f': {'item': 'xercamod:flask'}}, {'item': 'xercamod:flask'}, "", type="xercamod:crafting_condition_shaped_ender_flask"),

    ShapedRecipe(['kk', 'pp', 'pp'], {'item': 'xercamod:carving_station'},  {'p': {'tag': 'minecraft:planks'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "", type="xercamod:crafting_condition_shaped_carved_wood"),

    # Carved wood - didn't work because of mirroring
    # ShapedRecipe(['w ', ' k'], {'item': 'xercamod:carved_oak_1', 'count': 1}, {'w': {'item': 'minecraft:stripped_oak_log'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "carved_oak", "carved_wood", type="xercamod:crafting_condition_shaped_carved_wood"),
    # ShapedRecipe(['w', 'k'], {'item': 'xercamod:carved_oak_2', 'count': 1}, {'w': {'item': 'minecraft:stripped_oak_log'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "carved_oak", "carved_wood", type="xercamod:crafting_condition_shaped_carved_wood"),
    # ShapedRecipe([' w', 'k '], {'item': 'xercamod:carved_oak_3', 'count': 1}, {'w': {'item': 'minecraft:stripped_oak_log'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "carved_oak", "carved_wood", type="xercamod:crafting_condition_shaped_carved_wood"),
    # ShapedRecipe(['wk'], {'item': 'xercamod:carved_oak_4', 'count': 1}, {'w': {'item': 'minecraft:stripped_oak_log'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "carved_oak", "carved_wood", type="xercamod:crafting_condition_shaped_carved_wood"),
    # ShapedRecipe(['kw'], {'item': 'xercamod:carved_oak_5', 'count': 1}, {'w': {'item': 'minecraft:stripped_oak_log'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "carved_oak", "carved_wood", type="xercamod:crafting_condition_shaped_carved_wood"),
    # ShapedRecipe([' k', 'w '], {'item': 'xercamod:carved_oak_6', 'count': 1}, {'w': {'item': 'minecraft:stripped_oak_log'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "carved_oak", "carved_wood", type="xercamod:crafting_condition_shaped_carved_wood"),
    # ShapedRecipe(['k', 'w'], {'item': 'xercamod:carved_oak_7', 'count': 1}, {'w': {'item': 'minecraft:stripped_oak_log'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "carved_oak", "carved_wood", type="xercamod:crafting_condition_shaped_carved_wood"),
    # ShapedRecipe(['k ', ' w'], {'item': 'xercamod:carved_oak_8', 'count': 1}, {'w': {'item': 'minecraft:stripped_oak_log'}, 'k': {'item': 'xercamod:item_knife'}}, {'item': 'xercamod:item_knife'}, "carved_oak", "carved_wood", type="xercamod:crafting_condition_shaped_carved_wood"),
]

shapeless_recipes = [
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'xercamod:item_yoghurt'}], {'item': 'xercamod:item_ayran'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'minecraft:sweet_berries'}], {'item': 'xercamod:sweet_berry_juice'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'minecraft:apple'}], {'item': 'xercamod:item_apple_juice'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:gold_nugget'}, {'item': 'minecraft:cookie'}], {'item': 'xercamod:item_attorney_badge'}, {'item': 'minecraft:gold_nugget'}, "", type="xercamod:crafting_condition_shapeless_courtroom"),
    ShapelessRecipe([{'item': 'minecraft:bread'}, {'item': 'xercamod:item_knife', 'data': 32767}], {'item': 'xercamod:item_bun', 'count': 2}, {'item': 'minecraft:bread'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'minecraft:carrot'}], {'item': 'xercamod:item_carrot_juice'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:paper'}, {'item': 'minecraft:cyan_dye'}, {'item': 'minecraft:magenta_dye'}, {'item': 'minecraft:yellow_dye'}], {'item': 'xercamod:item_confetti', 'count': 12}, {'item': 'minecraft:paper'}, "", type="xercamod:crafting_condition_shapeless_confetti"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'minecraft:milk_bucket'}], {'item': 'xercamod:item_glass_of_milk'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'minecraft:water_bucket'}], {'item': 'xercamod:item_glass_of_water'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_knife'}, {'item': 'minecraft:fishing_rod'}], {'item': 'xercamod:item_grab_hook'}, {'item': 'minecraft:fishing_rod'}, "", type="xercamod:crafting_condition_shapeless_grab_hook"),
    ShapelessRecipe([{'item': 'xercamod:item_tea_dried'}, {'item': 'xercamod:item_glass_of_water'}, {'item': 'minecraft:snowball'}, {'item': 'minecraft:sugar'}], {'item': 'xercamod:item_ice_tea'}, {'item': 'xercamod:item_glass_of_water'}, "", type="xercamod:crafting_condition_shapeless_tea"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'minecraft:melon'}], {'item': 'xercamod:item_melon_juice'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:potato'}, {'item': 'xercamod:item_knife', 'data': 32767}], {'item': 'xercamod:item_potato_slices', 'count': 2}, {'item': 'minecraft:potato'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:gold_nugget'}, {'item': 'minecraft:poppy', 'data': 0}], {'item': 'xercamod:item_prosecutor_badge'}, {'item': 'minecraft:gold_nugget'}, "pro_badge", type="xercamod:crafting_condition_shapeless_courtroom"),
    ShapelessRecipe([{'item': 'minecraft:gold_nugget'}, {'item': 'minecraft:dandelion', 'data': 0}], {'item': 'xercamod:item_prosecutor_badge'}, {'item': 'minecraft:gold_nugget'}, "pro_badge", type="xercamod:crafting_condition_shapeless_courtroom"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'minecraft:pumpkin'}], {'item': 'xercamod:item_pumpkin_juice'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:chicken'}, {'item': 'xercamod:item_knife', 'data': 32767}], {'item': 'xercamod:item_raw_chicken_patty', 'count': 2}, {'item': 'minecraft:chicken'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:beef'}, {'item': 'xercamod:item_knife', 'data': 32767}], {'item': 'xercamod:item_raw_patty', 'count': 2}, {'item': 'minecraft:beef'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:porkchop'}, {'item': 'xercamod:item_knife', 'data': 32767}], {'item': 'xercamod:item_raw_sausage', 'count': 2}, {'item': 'minecraft:porkchop'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:sugar'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:cyan_dye'}, {'item': 'minecraft:magenta_dye'}, {'item': 'minecraft:yellow_dye'}], {'item': 'xercamod:item_sprinkles', 'count': 12}, {'item': 'minecraft:sugar'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'xercamod:item_tomato'}], {'item': 'xercamod:item_tomato_juice'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_tomato'}], {'item': 'xercamod:item_tomato_seeds'}, {'item': 'xercamod:item_tomato'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_tomato'}, {'item': 'xercamod:item_knife', 'data': 32767}], {'item': 'xercamod:item_tomato_slices', 'count': 3}, {'item': 'xercamod:item_tomato'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'minecraft:wheat'}, {'item': 'minecraft:wheat'}], {'item': 'xercamod:item_wheat_juice'}, {'item': 'xercamod:item_glass'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_block_straw'}], {'item': 'minecraft:sugar_cane', 'count': 9}, {'item': 'xercamod:item_block_straw'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_block_leather'}], {'item': 'minecraft:leather', 'count': 9}, {'item': 'xercamod:item_block_leather'}, ""),
    ShapelessRecipe([{'item': 'minecraft:gold_nugget'}], {'item': 'xercamod:item_golden_coin_5', 'count': 2}, {'item': 'minecraft:gold_nugget'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_golden_coin_5'}], {'item': 'xercamod:item_golden_coin_1', 'count': 5}, {'item': 'xercamod:item_golden_coin_5'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_golden_coin_5'}, {'item': 'xercamod:item_golden_coin_5'}], {'item': 'minecraft:gold_nugget'}, {'item': 'xercamod:item_golden_coin_5'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_golden_coin_1'}, {'item': 'xercamod:item_golden_coin_1'}, {'item': 'xercamod:item_golden_coin_1'}, {'item': 'xercamod:item_golden_coin_1'}, {'item': 'xercamod:item_golden_coin_1'}], {'item': 'xercamod:item_golden_coin_5'}, {'item': 'xercamod:item_golden_coin_1'}, ""),

    ShapelessRecipe([{'item': 'xercamod:item_knife', 'data': 32767}, {'item': 'minecraft:salmon'}], {'item': 'xercamod:sashimi', 'count': 2}, {'item': 'xercamod:cooked_rice'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:cooked_rice'}, {'item': 'minecraft:dried_kelp'}], {'item': 'xercamod:riceball', 'count': 2}, {'item': 'xercamod:cooked_rice'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:cooked_rice'}, {'item': 'minecraft:dried_kelp'}, {'item': 'xercamod:sashimi'}], {'item': 'xercamod:sushi', 'count': 2}, {'item': 'xercamod:cooked_rice'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:cooked_rice'}, {'item': 'xercamod:sashimi'}], {'item': 'xercamod:nigiri_sushi'}, {'item': 'xercamod:cooked_rice', 'count': 2}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:cooked_rice'}, {'item': 'xercamod:item_fried_egg'}], {'item': 'xercamod:omurice'}, {'item': 'xercamod:cooked_rice'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:cooked_rice'}, {'item': 'xercamod:item_fried_egg'}, {'item': 'minecraft:dried_kelp'}], {'item': 'xercamod:egg_sushi', 'count': 2}, {'item': 'xercamod:cooked_rice'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:item_glass'}, {'item': 'xercamod:item_rice_seeds'}, {'item': 'xercamod:item_rice_seeds'}], {'item': 'xercamod:sake'}, {'item': 'xercamod:item_rice_seeds'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:cooked_rice'}, {'item': 'minecraft:cooked_beef'}, {'item': 'minecraft:bowl'}], {'item': 'xercamod:beef_donburi'}, {'item': 'xercamod:cooked_rice'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:cooked_rice'}, {'item': 'minecraft:cooked_chicken'}, {'item': 'minecraft:bowl'}, {'item': 'xercamod:item_fried_egg'}], {'item': 'xercamod:oyakodon'}, {'item': 'xercamod:cooked_rice'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:cooked_rice'}, {'item': 'minecraft:sugar'}, {'item': 'minecraft:bowl'}, {'item': 'minecraft:milk_bucket'}], {'item': 'xercamod:rice_pudding'}, {'item': 'xercamod:item_rice_seeds'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'xercamod:doner_slice'}, {'item': 'xercamod:item_yoghurt'}, {'item': 'xercamod:item_tomato_slices'}, {'item': 'minecraft:bread'}, {'item': 'minecraft:bowl'}], {'item': 'xercamod:item_alexander'}, {'item': 'xercamod:doner_slice'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:sweet_berries'}, {'item': 'xercamod:item_yoghurt'}, {'item': 'minecraft:honey_bottle'}, {'item': 'minecraft:bowl'}], {'item': 'xercamod:item_honeyberry_yoghurt'}, {'item': 'xercamod:item_yoghurt'}, "", type="xercamod:crafting_condition_shapeless_food"),
    ShapelessRecipe([{'item': 'minecraft:mutton'}, {'item': 'minecraft:stick'}, {'item': 'xercamod:item_tomato_slices'}], {'item': 'xercamod:raw_shish_kebab'}, {'item': 'minecraft:mutton'}, "", type="xercamod:crafting_condition_shapeless_food"),


    ShapelessRecipe([{'item': 'xercamod:item_knife', 'data': 32767}, {'item': 'minecraft:acacia_log'}], {'item': 'minecraft:stripped_acacia_log'}, {'item': 'xercamod:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_knife', 'data': 32767}, {'item': 'minecraft:birch_log'}], {'item': 'minecraft:stripped_birch_log'}, {'item': 'xercamod:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_knife', 'data': 32767}, {'item': 'minecraft:dark_oak_log'}], {'item': 'minecraft:stripped_dark_oak_log'}, {'item': 'xercamod:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_knife', 'data': 32767}, {'item': 'minecraft:jungle_log'}], {'item': 'minecraft:stripped_jungle_log'}, {'item': 'xercamod:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_knife', 'data': 32767}, {'item': 'minecraft:oak_log'}], {'item': 'minecraft:stripped_oak_log'}, {'item': 'xercamod:item_knife'}, ""),
    ShapelessRecipe([{'item': 'xercamod:item_knife', 'data': 32767}, {'item': 'minecraft:spruce_log'}], {'item': 'minecraft:stripped_spruce_log'}, {'item': 'xercamod:item_knife'}, ""),

    ShapelessRecipe([{'item': 'minecraft:string'}, {'item': 'minecraft:string'}, {'item': 'minecraft:string'}], {'item': 'xercamod:rope'}, {'item': 'minecraft:string'}, ""),
]

cooking_recipes = [
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:rice_pudding'}, "xercamod:baked_rice_pudding", 0.2, 250, {'item': 'xercamod:rice_pudding'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_raw_chicken_patty'}, "xercamod:item_cooked_chicken_patty", 0.2, 200, {'item': 'xercamod:item_raw_chicken_patty'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'minecraft:egg'}, "xercamod:item_fried_egg", 0.2, 200, {'item': 'minecraft:egg'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_raw_patty'}, "xercamod:item_cooked_patty", 0.2, 200, {'item': 'xercamod:item_raw_patty'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_potato_slices'}, "xercamod:item_potato_fries", 0.2, 200, {'item': 'xercamod:item_potato_slices'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_raw_sausage'}, "xercamod:item_cooked_sausage", 0.2, 200, {'item': 'xercamod:item_raw_sausage'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_raw_schnitzel'}, "xercamod:item_cooked_schnitzel", 0.2, 200, {'item': 'xercamod:item_raw_schnitzel'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_tea_leaf'}, "xercamod:item_tea_dried", 0.1, 200, {'item': 'xercamod:item_tea_leaf'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_full_teapot_1'}, "xercamod:item_hot_teapot_1", 0.1, 100, {'item': 'xercamod:item_full_teapot_1'}, "hot_teapot"),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_full_teapot_2'}, "xercamod:item_hot_teapot_2", 0.15, 150, {'item': 'xercamod:item_full_teapot_2'}, "hot_teapot"),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_full_teapot_3'}, "xercamod:item_hot_teapot_3", 0.2, 200, {'item': 'xercamod:item_full_teapot_3'}, "hot_teapot"),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_full_teapot_4'}, "xercamod:item_hot_teapot_4", 0.25, 250, {'item': 'xercamod:item_full_teapot_4'}, "hot_teapot"),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_full_teapot_5'}, "xercamod:item_hot_teapot_5", 0.3, 300, {'item': 'xercamod:item_full_teapot_5'}, "hot_teapot"),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_full_teapot_6'}, "xercamod:item_hot_teapot_6", 0.35, 350, {'item': 'xercamod:item_full_teapot_6'}, "hot_teapot"),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_full_teapot_7'}, "xercamod:item_hot_teapot_7", 0.4, 400, {'item': 'xercamod:item_full_teapot_7'}, "hot_teapot"),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:item_rice_seeds'}, "xercamod:cooked_rice", 0.2, 200, {'item': 'xercamod:item_rice_seeds'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'minecraft:milk_bucket'}, "xercamod:item_yoghurt", 0.2, 200, {'item': 'minecraft:milk_bucket'}, ""),
    CookingRecipe("minecraft:smelting", {'item': 'xercamod:raw_shish_kebab'}, "xercamod:item_shish_kebab", 0.2, 200, {'item': 'xercamod:raw_shish_kebab'}, ""),
]

special_recipes = [
    SpecialRecipe("xercamod:crafting_special_flask_filling", None, ""),
    SpecialRecipe("xercamod:crafting_special_ender_bow_filling", None, ""),
    SpecialRecipe("xercamod:crafting_special_flask_milk_filling", None, ""),
    SpecialRecipe("xercamod:crafting_special_tea_filling", None, ""),
    SpecialRecipe("xercamod:crafting_special_tea_pouring", None, ""),
    SpecialRecipe("xercamod:crafting_special_tea_refilling", None, ""),
    SpecialRecipe("xercamod:crafting_special_tea_sugaring", None, ""),
    SpecialRecipe("xercamod:crafting_special_wood_carving", None, ""),
]

stonecutting_recipes = [
    StonecuttingRecipe("xercamod:black_terratile", "xercamod:black_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:blue_terratile", "xercamod:blue_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:brown_terratile", "xercamod:brown_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:cyan_terratile", "xercamod:cyan_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:gray_terratile", "xercamod:gray_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:green_terratile", "xercamod:green_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:light_blue_terratile", "xercamod:light_blue_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:light_gray_terratile", "xercamod:light_gray_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:lime_terratile", "xercamod:lime_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:magenta_terratile", "xercamod:magenta_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:orange_terratile", "xercamod:orange_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:pink_terratile", "xercamod:pink_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:purple_terratile", "xercamod:purple_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:red_terratile", "xercamod:red_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:white_terratile", "xercamod:white_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:yellow_terratile", "xercamod:yellow_terratile_slab", 2, "", "terratile"),
    StonecuttingRecipe("xercamod:terratile", "xercamod:terratile_slab", 2, "", "terratile"),

    StonecuttingRecipe("xercamod:black_terratile", "xercamod:black_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:blue_terratile", "xercamod:blue_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:brown_terratile", "xercamod:brown_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:cyan_terratile", "xercamod:cyan_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:gray_terratile", "xercamod:gray_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:green_terratile", "xercamod:green_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:light_blue_terratile", "xercamod:light_blue_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:light_gray_terratile", "xercamod:light_gray_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:lime_terratile", "xercamod:lime_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:magenta_terratile", "xercamod:magenta_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:orange_terratile", "xercamod:orange_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:pink_terratile", "xercamod:pink_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:purple_terratile", "xercamod:purple_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:red_terratile", "xercamod:red_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:white_terratile", "xercamod:white_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:yellow_terratile", "xercamod:yellow_terratile_stairs", 1, "", "terratile"),
    StonecuttingRecipe("xercamod:terratile", "xercamod:terratile_stairs", 1, "", "terratile"),

    StonecuttingRecipe("minecraft:black_terracotta", "xercamod:black_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:blue_terracotta", "xercamod:blue_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:brown_terracotta", "xercamod:brown_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:cyan_terracotta", "xercamod:cyan_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:gray_terracotta", "xercamod:gray_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:green_terracotta", "xercamod:green_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:light_blue_terracotta", "xercamod:light_blue_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:light_gray_terracotta", "xercamod:light_gray_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:lime_terracotta", "xercamod:lime_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:magenta_terracotta", "xercamod:magenta_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:orange_terracotta", "xercamod:orange_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:pink_terracotta", "xercamod:pink_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:purple_terracotta", "xercamod:purple_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:red_terracotta", "xercamod:red_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:white_terracotta", "xercamod:white_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:yellow_terracotta", "xercamod:yellow_terratile", 1, "", "terratile"),
    StonecuttingRecipe("minecraft:terracotta", "xercamod:terratile", 1, "", "terratile"),
]

carving_recipes = [
    CarvingRecipe("minecraft:oak_log", "minecraft:stripped_oak_log", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercamod:carved_oak_1", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercamod:carved_oak_2", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercamod:carved_oak_3", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercamod:carved_oak_4", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercamod:carved_oak_5", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercamod:carved_oak_6", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercamod:carved_oak_7", 1, "", "carving"),
    CarvingRecipe("minecraft:oak_log", "xercamod:carved_oak_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercamod:carved_oak_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercamod:carved_oak_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercamod:carved_oak_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercamod:carved_oak_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercamod:carved_oak_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercamod:carved_oak_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercamod:carved_oak_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_oak_log", "xercamod:carved_oak_8", 1, "", "carving"),

    CarvingRecipe("minecraft:birch_log", "minecraft:stripped_birch_log", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercamod:carved_birch_1", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercamod:carved_birch_2", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercamod:carved_birch_3", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercamod:carved_birch_4", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercamod:carved_birch_5", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercamod:carved_birch_6", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercamod:carved_birch_7", 1, "", "carving"),
    CarvingRecipe("minecraft:birch_log", "xercamod:carved_birch_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercamod:carved_birch_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercamod:carved_birch_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercamod:carved_birch_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercamod:carved_birch_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercamod:carved_birch_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercamod:carved_birch_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercamod:carved_birch_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_birch_log", "xercamod:carved_birch_8", 1, "", "carving"),

    CarvingRecipe("minecraft:spruce_log", "minecraft:stripped_spruce_log", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercamod:carved_spruce_1", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercamod:carved_spruce_2", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercamod:carved_spruce_3", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercamod:carved_spruce_4", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercamod:carved_spruce_5", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercamod:carved_spruce_6", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercamod:carved_spruce_7", 1, "", "carving"),
    CarvingRecipe("minecraft:spruce_log", "xercamod:carved_spruce_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercamod:carved_spruce_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercamod:carved_spruce_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercamod:carved_spruce_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercamod:carved_spruce_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercamod:carved_spruce_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercamod:carved_spruce_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercamod:carved_spruce_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_spruce_log", "xercamod:carved_spruce_8", 1, "", "carving"),

    CarvingRecipe("minecraft:jungle_log", "minecraft:stripped_jungle_log", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercamod:carved_jungle_1", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercamod:carved_jungle_2", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercamod:carved_jungle_3", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercamod:carved_jungle_4", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercamod:carved_jungle_5", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercamod:carved_jungle_6", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercamod:carved_jungle_7", 1, "", "carving"),
    CarvingRecipe("minecraft:jungle_log", "xercamod:carved_jungle_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercamod:carved_jungle_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercamod:carved_jungle_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercamod:carved_jungle_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercamod:carved_jungle_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercamod:carved_jungle_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercamod:carved_jungle_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercamod:carved_jungle_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_jungle_log", "xercamod:carved_jungle_8", 1, "", "carving"),

    CarvingRecipe("minecraft:acacia_log", "minecraft:stripped_acacia_log", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercamod:carved_acacia_1", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercamod:carved_acacia_2", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercamod:carved_acacia_3", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercamod:carved_acacia_4", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercamod:carved_acacia_5", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercamod:carved_acacia_6", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercamod:carved_acacia_7", 1, "", "carving"),
    CarvingRecipe("minecraft:acacia_log", "xercamod:carved_acacia_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercamod:carved_acacia_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercamod:carved_acacia_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercamod:carved_acacia_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercamod:carved_acacia_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercamod:carved_acacia_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercamod:carved_acacia_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercamod:carved_acacia_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_acacia_log", "xercamod:carved_acacia_8", 1, "", "carving"),

    CarvingRecipe("minecraft:dark_oak_log", "minecraft:stripped_dark_oak_log", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercamod:carved_dark_oak_1", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercamod:carved_dark_oak_2", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercamod:carved_dark_oak_3", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercamod:carved_dark_oak_4", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercamod:carved_dark_oak_5", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercamod:carved_dark_oak_6", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercamod:carved_dark_oak_7", 1, "", "carving"),
    CarvingRecipe("minecraft:dark_oak_log", "xercamod:carved_dark_oak_8", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercamod:carved_dark_oak_1", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercamod:carved_dark_oak_2", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercamod:carved_dark_oak_3", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercamod:carved_dark_oak_4", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercamod:carved_dark_oak_5", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercamod:carved_dark_oak_6", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercamod:carved_dark_oak_7", 1, "", "carving"),
    CarvingRecipe("minecraft:stripped_dark_oak_log", "xercamod:carved_dark_oak_8", 1, "", "carving"),
]

smithing_recipes = [
    SmithingRecipe("xercamod:diamond_scythe", "minecraft:netherite_ingot", "xercamod:netherite_scythe"),
    SmithingRecipe("xercamod:item_diamond_warhammer", "minecraft:netherite_ingot", "xercamod:item_netherite_warhammer")
]

campfire_recipes = []
smoker_recipes = []

for r in cooking_recipes:
    campfire_recipe = deepcopy(r)
    campfire_recipe.type = "minecraft:campfire_cooking"
    campfire_recipe.cooking_time *= 3
    campfire_recipes.append(campfire_recipe)

    smoker_recipe = deepcopy(r)
    smoker_recipe.type = "minecraft:smoking"
    smoker_recipe.cooking_time = int(smoker_recipe.cooking_time*0.5)
    smoker_recipes.append(smoker_recipe)

all_recipes = [r for l in [shaped_recipes, shapeless_recipes, cooking_recipes, special_recipes, campfire_recipes, smoker_recipes, stonecutting_recipes, carving_recipes, smithing_recipes] for r in l]


# generate_recipe_code_from_files("xercamod")
clean_recipe_jsons("xercamod")
generate_recipe_jsons(all_recipes, "xercamod")
