# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.80
# Mod Properties
mod_id=xercaomnichest
mod_name=Omni Chest
mod_version=26.1.2-1.0.0
mod_license=GPL-3.0
mod_group_id=xerca
